### ISSUE TITLE
Firefox on F33 Silverblue is outdated

### ISSUE THREAD

**Issue by sukahiroaki** [fedora-silverblue/issue-tracker#85] opened 2020-09-19 07:59 UTC
Title says it all: F33 Silverblue currently delivers Firefox 78.0.1, while on F32 Silverblue (and Workstation) you are getting the actual recent release 80.0.1.

**Comment by tpopela** [comment] 2020-09-19 08:28
That is kind of expected as there was not a successful build of Firefox for F33 for a long time due to GCC bugs (look at https://koji.fedoraproject.org/koji/packageinfo?packageID=37). But recently it was fixed, but the F33 probably slipped through. I will ask the maintainers to do a F33 build on Monday.

**Comment by tpopela** [comment] 2020-09-19 08:30
I was actually wrong and there were no successful builds for F34 either, so the issue is still not fixed.

**Comment by sukahiroaki** [comment] 2020-09-19 09:02
Thanks for the clarification. Well at least there is the Flatpak which is up to date...

**Comment by kalev** [comment] 2020-09-21 07:57
I wonder if we should start shipping Firefox flatpak instead of rpm as default on Silverblue?

**Comment by tpopela** [comment] 2020-09-21 09:14
At this point no, but one of our plans for the next quarter is to go through all the "Firefox in a Flatpak" pain points and set some plan.

**Comment by A6GibKm** [comment] 2020-09-28 23:03
It is even possible for a Firefox flatpak built by fedora to use the ffmpeg extensions from flathub (as far as I know the runtimes are incompatible)? Time for a "`flatpak-fusion`" third party repository? 

If it is not possible to use proper codecs iit might not be a good idea. To have the user remove the flatpak from `fedora` to install the one from `flathub` is no different than the current status.

**Comment by tpopela** [comment] 2020-10-08 09:25
Closing as the Firefox is up to date in Silverblue.

**Closed by tpopela** 2020-10-08 09:25 UTC
