### ISSUE TITLE
Replace Cheese with Snapshot as the default camera application

### ISSUE THREAD

**Issue by EliasOfWaffle** [fedora-silverblue/issue-tracker#480] opened 2023-07-08 16:52 UTC
**Is your feature request related to a problem? Please describe.**
Gnome Cheese is old and the new app for photos is Gnome Snapshot

**Describe the solution you'd like**
Can be good replace Gnome Cheese to actual Gnome Snapshot

**Describe alternatives you've considered**

**Additional context**

**Comment by travier** [comment] 2023-07-09 11:39
Looks like this is https://gitlab.gnome.org/GNOME/Incubator/snapshot ?

This would probably be best to switch for both Workstation and Silverblue.

**Comment by EliasOfWaffle** [comment] 2023-07-09 21:11
> Looks like this is https://gitlab.gnome.org/GNOME/Incubator/snapshot ?
> 
> It would probably be best to switch both Workstation and Silverblue if we decide to do it.

yes can be good, have a actual plan from replacing in fedora ?
Or is necessary a change submission in change purpose?

**Comment by travier** [comment] 2023-07-10 07:14
Looks like this is already under discussion in the Workstation issue tracker: https://pagure.io/fedora-workstation/issue/166

**Comment by tpopela** [comment] 2023-07-10 09:34
Let's close this as a duplicate of the Fedora Workstation Working Group ticket - https://pagure.io/fedora-workstation/issue/166 - we will follow the decision of the group.

**Closed** 2023-07-10 09:34 UTC
Labels: enhancement
