### ISSUE TITLE
[Bug Report] akmods fails to build nvidia driver due to lack of dnf/yum

### ISSUE THREAD

**Issue by david-burkett** [fedora-silverblue/issue-tracker#356] opened 2022-09-20 16:40 UTC
**Describe the bug**

When attempting to build the nvidia kmod (secure boot enabled, key enrolled already etc), I get the following error output:

```
sudo akmods --force                                                                                                                                                                                                  
[sudo] password for user: 
Checking kmods exist for 5.19.9-200.fc36.x86_64 [  OK  ]
Building and installing nvidia-kmod [FAILED]
Could not install newly built RPMs. You can find them and the logfile in:
/var/cache/akmods/nvidia/515.65.01-1-for-5.19.9-200.fc36.x86_64.failed.log
 [FAILED]
```

When checking the logs for the reason of failure appears to be that it only checks for `dnf`/`yum`:

```
2022/09/20 12:19:14 akmodsbuild: RPM build warnings:
2022/09/20 12:19:14 akmodsbuild: user mockbuild does not exist - using root
2022/09/20 12:19:14 akmodsbuild: group mock does not exist - using root
2022/09/20 12:19:14 akmodsbuild: user mockbuild does not exist - using root
2022/09/20 12:19:14 akmodsbuild: group mock does not exist - using root
2022/09/20 12:19:14 akmods: Installing newly built rpms
2022/09/20 12:19:14 akmods: DNF not found, using YUM instead.
/usr/sbin/akmods: line 312: yum: command not found
2022/09/20 12:19:14 akmods: Could not install newly built RPMs. You can find them and the logfile in:
2022/09/20 12:19:14 akmods: /var/cache/akmods/nvidia/515.65.01-1-for-5.19.9-200.fc36.x86_64.failed.log
```

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. `sudo akmods --force`

**Expected behavior**
nvidia-kmod to be built and installed

**Screenshots**
![image](https://user-images.githubusercontent.com/45216760/191315646-350b5e42-43e5-4ca5-bba0-900116df6828.png)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                  Version: 36.20220920.0 (2022-09-20T02:13:17Z)
               BaseCommit: d845c735de2fe7a3a602b4faf28bfa3cc40dd295430bda94aa2622c35f28765b
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
          LayeredPackages: akmod-nvidia akmods gcc gstreamer-plugins-espeak
                           gstreamer1-plugin-openh264 kernel-devel kernel-headers kmodtool
                           openssl virt-manager xorg-x11-drv-nvidia
                           xorg-x11-drv-nvidia-libs xorg-x11-drv-nvidia-libs.i686 zsh
                Initramfs: regenerate
```

**Comment by travier** [comment] 2022-09-20 17:38
This is extremely likely to be a duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/272

**Closed by travier** 2022-09-20 17:38 UTC
Labels: bug, f36
