### ISSUE TITLE
System sound automatically turns off in fedora 33

### ISSUE THREAD

**Issue by mwaykole** [fedora-silverblue/issue-tracker#135] opened 2021-03-12 18:09 UTC

**Comment by milindw96** [comment] 2021-03-12 18:11
In the fedora 33 System sound automatically turn off
Additional info:
Mostly it happens when u use Headphones

**Comment by tpopela** [comment] 2021-05-04 08:44
Hi @milindw96 is this still an issue? Did you have PipeWire installed as a PulseAudio replacement?

**Comment by milindw96** [comment] 2021-05-05 07:02
yes the issue is still there 
pipewire is installed in my  system
pipewire0.2-libs-0.2.7-2.fc32.x86_64
pipewire-0.3.15-2.fc32.x86_64
pipewire-libs-0.3.15-2.fc32.x86_64

**Comment by milindw96** [comment] 2021-05-05 07:03
✘ mwaykole  ~  rpm -qa | grep -i PipeWire
pipewire0.2-libs-0.2.7-2.fc32.x86_64
pipewire-0.3.15-2.fc32.x86_64
pipewire-libs-0.3.15-2.fc32.x86_64
 mwaykole  ~  rpm -qa | grep -i PulseAudio
pulseaudio-module-bluetooth-14.0-1.fc32.x86_64
pulseaudio-14.0-1.fc32.x86_64
pulseaudio-utils-14.0-1.fc32.x86_64
pulseaudio-module-x11-14.0-1.fc32.x86_64
pulseaudio-libs-glib2-14.0-1.fc32.x86_64
alsa-plugins-pulseaudio-1.2.2-1.fc32.x86_64
pulseaudio-libs-14.0-1.fc32.x86_64

**Comment by tpopela** [comment] 2021-05-05 07:05
Is this on F32 or F33? (according to packages it's F32), but you said in the first comment that it's F33.

**Comment by milindw96** [comment] 2021-05-05 07:34
It's Fedora 32 sorry i missed to update it correctly

**Comment by tpopela** [comment] 2021-05-05 07:49
ok, on F32 PipeWire isn't used as a PulseAudio replacement, so I would suggest you to open a bug in https://bugzilla.redhat.com/enter_bug.cgi?component=pulseaudio&product=Fedora&version=32 - but as there's just few weeks of F32 cycle left, I would maybe try to update to F33 or F34 to see whether it's fixed (it's an easy thing to do with Silverblue). If the problems persist, then please report the bug, but change the Fedora version when creating the bug as the link that I've send you is for F32.

**Comment by HarryMichal** [comment] 2022-01-15 02:37
Hi @milindw96! Is this issue still present on your system?

**Comment by milindw96** [comment] 2022-01-20 14:42
yup sometime i still see the issue its like 5/10

**Comment by HarryMichal** [comment] 2022-01-22 14:19
Even on a recent release of Fedora. I don't recall encountering the issue myself. Could you possibly describe in more detail how can the event be triggered?

**Comment by milindw96** [comment] 2022-01-25 04:41
I couldn't find any trigger point for it.. but I can say that if I am connected with HDMI (to share the screen ) then only it happens... but it's not always

**Comment by alvarlagerlof** [comment] 2022-05-31 14:31
I have this issue too

**Comment by travier** [comment] 2022-06-01 11:05
This is now an old and un-diagnosed issue. Thus please provide at minimum the following information when commenting here:
- output of `rpm-ostree status`
- whether you are using pulseaudio or pipewire
- consider commenting on https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1214 with more info.

**Comment by travier** [comment] 2023-05-15 16:32
Fedora 36 is about to go EOL so I'll close this issue. Please provide updated information if this is still an issue.

**Closed by travier** 2023-05-15 16:32 UTC
Labels: bug, need-info
