### ISSUE TITLE
Bug: Unprivileged Users getting "sudo prompts" for updates

### ISSUE THREAD

**Issue by dschier-wtd** [fedora-silverblue/issue-tracker#55] opened 2020-05-04 07:10 UTC
I am running Fedora 32 Silverblue. I have two users on my system, one is "Administrator", one is not. When using the unprivileged user, I am getting the gnome dialog to unlock updates every now and then.

Even more interesting, the prompt points to the administrator user and not the currently used unprivileged user.

My expected behavior would be, that either the user cannot update at all or the prompt will occur only when manual updates are triggered.

**Comment by tpopela** [comment] 2020-05-05 11:49
I talked yesterday with Kalev and he thinks that something should indeed change. Right now it's as it's should be - the members of the wheel group have rights for the following operations - https://src.fedoraproject.org/rpms/fedora-release/blob/master/f/org.projectatomic.rpmostree1.rules. So it probably means, that we have to disable the automatic updates through GNOME Software for unprivileged users or found any other solution.

**Comment by daniel-wtd** [comment] 2020-05-09 09:51
Hmmm, that may interrupt the regular popups. As soon as the user opens gnome-software he may be asked for a privileged password again. Therefore I think:

- unprivileged user should only be allowed to interact with user repos per default
- an „unlock mechanism“ as used in gnome-settings would be helpful.

**Comment by allisonkarlitskaya** [comment] 2020-11-12 08:12
I just opened my laptop after suspend and had to press the escape key *7* times in order to dismiss these dialogs.  Then I started writing a message in Telegram and the dialog popped up 3 more times in the middle of me writing that message (causing me to type a few characters into it each time, before I dismissed it).

This is easily the most serious bug in Silverblue right now.

I'm on a fresh install of Fedora 33 Silverblue, by the way.

**Comment by allisonkarlitskaya** [comment] 2020-11-12 08:29
The polkit authentication in question is:

```
Nov 12 09:26:36 x1 polkitd[795]: <no filename>:6: action=[Action id='org.projectatomic.rpmostree1.repo-refresh']
Nov 12 09:26:36 x1 polkitd[795]: <no filename>:7: subject=[Subject pid=1846 user='lis' groups=lis seat=null session=null local=true active=true]
```

pid 1846 is

```
   1846 ?        Sl     0:01 /usr/bin/gnome-software --gapplication-service
```

The two automatic update options in the gnome-software preferences UI are disabled.

**Comment by allisonkarlitskaya** [comment] 2020-11-12 08:38
This is being triggered from `rpm-ostree` `src/daemon/rpmostreed-os.c:os_authorize_method()` in response to a `RefreshMd` D-Bus call from the rpm-ostree plugin of gnome-software.

In turn, that's happening because of a call to `gs_plugin_refresh()` on the plugin.  Note: this is not an attempt to install updates.  It's only an attempt to refresh the list of available updates.

One fix might me to make this operation available to all locally-logged-in users.  It seems pretty harmless?  Probably we'd want to ask `rpm-ostree` authors, though, because `RefreshMd` has an `options` parameter, which could possibly be dangerous.

Another fix is to make `gnome-software` not do this refresh for the rpm-ostree plugin in the background.

**Comment by allisonkarlitskaya** [comment] 2020-11-12 08:54
`/usr/share/polkit-1/rules.d/org.projectatomic.rpmostree1.rules` is in package `fedora-release-identity-silverblue-33-2.noarch` which makes it seem like this bug is definitely a Silverblue issue.

**Comment by allisonkarlitskaya** [comment] 2020-11-12 09:44
I've filed a (potentially completely bogus) pull request here: https://src.fedoraproject.org/rpms/fedora-release/pull-request/159

**Comment by jlebon** [comment] 2020-11-12 19:12
Not against opening it up for `RefreshMd`, though I think it'd be cleaner to just have g-s not try to update anything if the user isn't an admistrator.

**Comment by daniel-wtd** [comment] 2020-11-16 07:03
@jlebon sounds absolutely perfect for me. Unprivileged users shouldnt be able to install/update system wide software. Its a different story for "user flatpak" remotes.

**Comment by allisonkarlitskaya** [comment] 2020-11-16 07:30
> @jlebon sounds absolutely perfect for me. Unprivileged users shouldnt be able to install/update system wide software. Its a different story for "user flatpak" remotes.

I disagree with this.  I think it's completely fine to be able to update/install software as an unprivileged user, subject to authentication.  That's what the prompt is for.  The thing that I object to is getting prompts at login when I didn't take any action.

**Comment by allisonkarlitskaya** [comment] 2020-11-16 07:31
Btw: After testing with the patch from https://src.fedoraproject.org/rpms/fedora-release/pull-request/159 applied for a while, I notice a new issue:

```
Nov 16 08:26:54 x1 polkitd[783]: <no filename>:2: action=[Action id='org.freedesktop.Flatpak.metadata-update']
Nov 16 08:26:54 x1 polkitd[783]: <no filename>:3: subject=[Subject pid=1815 user='lis' groups=lis seat=null session=null local=true active=true]
```

**Comment by HarryMichal** [comment] 2022-01-15 02:31
An upstream issue exists that may be connected to this: https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1561

**Comment by travier** [comment] 2022-08-19 22:25
Closing as https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1561 has been closed. Feel free to comment here if this is still an issue.

**Closed by travier** 2022-08-19 22:25 UTC

**Comment by andreldmonteiro** [comment] 2025-04-19 22:20
I had a gnome GUI password prompt recently, I don't know if this has anything to do with it but may be reproducible, I think gnome software was checking for updates on the background and I changed to a VT and changed back to gnome and the prompt was there, I cancelled it, didn't enter the password. 

Maybe doing that can trigger something like that? I had it happened before but it was so rare I think was only one more time and it was a while ago.
