### ISSUE TITLE
[BUG] Installer doesn't set appropriate keymap

### ISSUE THREAD

**Issue by JayDoubleu** [fedora-silverblue/issue-tracker#229] opened 2022-01-01 16:31 UTC
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
Silverblue keymap seems to always default to english post installation.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. During installation, set installer language to english
2. Change keymap to German (DE)
3. Remove English keymap from the list
4. Configure LUKS encryption and Install silverblue
5. Boot to installed system

**Expected behavior**
LUKS should have it's default keymap set to DE

**Screenshots**

**OS version:**
```
Silverblue 35
```

**Additional context**
Setting keymap in live grub menu to `vconsole.keymap=de` allows the LUKS password to be set in DE.

When reproducing on Fedora Workstation 35, after installation LUKS is set to "DE" keymap by default.

**Comment by tpopela** [comment] 2022-01-03 14:15
Duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/3

**Closed by tpopela** 2022-01-03 14:15 UTC
