### ISSUE TITLE
rpm commands erroring

### ISSUE THREAD

**Issue by daniel-wtd** [fedora-silverblue/issue-tracker#105] opened 2020-11-17 12:31 UTC
Hi, since some days, I am getting the below warnings/errors when using rpm commands:

```
rpm -qa | grep podman
warning: Found bdb Packages database while attempting sqlite backend: using bdb backend.
podman-2.1.1-12.fc33.x86_64
podman-plugins-2.1.1-12.fc33.x86_64
```

I have tried to rebuild the db:

```
rpm -v --rebuilddb
# or
rpmdb -v --rebuildb
```
Both are exiting (exit 1), without any usable information.

In case any addtional information is needed, please don't hesitate to inform me.

**Comment by jlebon** [comment] 2020-11-17 20:29
See https://github.com/coreos/fedora-coreos-tracker/issues/623 and https://github.com/coreos/rpm-ostree/pull/2221. TL;DR: Silverblue is currently shipping with bdb instead of sqlite to make rebases from f32 smoother. TBD when the switch to sqlite happens (with the upper-bound being f34).

**Comment by tpopela** [comment] 2020-11-18 11:12
Duplicate of 95

**Closed by tpopela** 2020-11-18 11:12 UTC
