### ISSUE TITLE
Multiple issues after upgrade

### ISSUE THREAD

**Issue by Verhoeckx** [fedora-silverblue/issue-tracker#235] opened 2022-01-28 22:42 UTC
**Describe the bug**
After upgrading from version 35.20220117.0 to version 35.20220128.0 I experience the following issues:
1. No sound and/or the sound card doesn't seem to be recognized.
2. A lot of (GTK) applications don't start anymore.

<br>

**To Reproduce**
1. Run version 35.20220117.0 of Fedora Silverblue
2. Upgrade to version 35.20220128.0

<br>

**Expected behavior**
Sound card should be recognized and all GTK applications should start normally.

<br>

**Screenshots**
![Screenshot from 2022-01-28 23-33-10](https://user-images.githubusercontent.com/64807887/151630800-06eb9eed-80f4-4766-8b64-188b68924a1e.png)

<br>

**OS version:**
Fedora Silverblue  35.20220128.0

```
State: idle
BootedDeployment:
● fedora:fedora/35/x86_64/silverblue
                   Version: 35.20220128.0 (2022-01-28T00:46:33Z)
                BaseCommit: 9b4b488e2bd4eaf808067fc983153b840c3741c7077d04125a44b754274f9233
              GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F
           LayeredPackages: ffmpeg gnome-tweak-tool nautilus-dropbox simple-scan thai-scalable-purisa-fonts vim xsane
             LocalPackages: Publii-0.38.2-1.x86_64 rpmfusion-free-release-35-1.noarch rpmfusion-nonfree-release-35-1.noarch
                            uld-1.00.39-1.fc34.x86_64
```

<br>

**Additional context**
[output_dmesg.txt](https://github.com/fedora-silverblue/issue-tracker/files/7962241/output_dmesg.txt)

<br>

**systemctl --user enable --now wireplumber**
```
Failed to enable unit: Process org.freedesktop.systemd1 exited with status 1
```

<br>

 **systemctl --user status session.slice**
```
Failed to get properties: Process org.freedesktop.systemd1 exited with status 1
```

<br>

_Let me know which commands I have to run to give you more information about my system!_
_In the meantime, I will do a rollback: version 35.20220117.0 worked without any issues._

**Comment by Verhoeckx** [comment] 2022-02-10 12:41
I'm not sure if this is a coincidence, but I also have a Dell XPS 13!
On my other (work) laptop, a HP laptop, I don't have any problems.

**Comment by HarryMichal** [comment] 2022-02-10 13:55
I believe this is a duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/234.

Workaround mentioned in https://github.com/fedora-silverblue/issue-tracker/issues/234#issuecomment-1020879508 has worked for the poster and me.

**Comment by Verhoeckx** [comment] 2022-02-11 19:52
> I had very similar issues after upgrade from `35.20211229.0` to `35.20220210.0` (no sound devices, unable to connect with bluetooth devices nor pair new ones, some applications and command being very slow). I discussed it with @HarryMichal and https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_selinux_problems was the solution for me.

_And this worked for me too :tada: !!_

**Comment by jkonecny12** [comment] 2022-02-15 11:10
If I'm not mistaken you are encountering this issue https://bugzilla.redhat.com/show_bug.cgi?id=2042157 ?

**Comment by travier** [comment] 2022-08-19 22:47
Likely due to an outdated SELinux policy. Closing as we have fixes in rpm-ostree & SELinux utils for that now.

**Closed by travier** 2022-08-19 22:47 UTC
