### ISSUE TITLE
[BUG] Upgraded package incorrectly characterized as a "downgrade"

### ISSUE THREAD

**Issue by cjao** [fedora-silverblue/issue-tracker#171] opened 2021-05-14 09:50 UTC
**Describe the bug**
My system is currently running version 34.20210506, and I see a pending update to 34.20210512. `rpm-ostree db diff` shows the following line:
`Downgraded:
  firefox 88.0-7.fc34 -> 88.0.1-1.fc34`

**Expected behavior**
If I understand version strings correctly, 88.0.1-1 is newer than 88.0-7

**Screenshots**

**OS version:**
```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 1 day 15h ago
BootedDeployment:
● ostree://fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210506.0 (2021-05-06T00:46:06Z)
                BaseCommit: 6094ea9b5d57ba9448b3fe8733df1d9aea4b9c1a4649b567e46f91f726b8da99
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: distribution-gpg-keys eog fedora-workstation-repositories ffmpeg-libs gnome-boxes
                            gnome-shell-extension-appindicator nautilus-dropbox simple-scan virt-manager

```

**Comment by tpopela** [comment] 2021-05-14 09:57
No, it's right - see
```
0 $ rpmdev-vercmp firefox-88.0-8.fc34 firefox-88.0.1-1.fc34
WARNING: hyphen in release1: 88.0-8.fc34
WARNING: hyphen in release2: 88.0.1-1.fc34

rpmdev-vercmp <epoch1> <ver1> <release1> <epoch2> <ver2> <release2>
rpmdev-vercmp <EVR1> <EVR2>
rpmdev-vercmp # with no arguments, prompt

Exit status is 0 if the EVR's are equal, 11 if EVR1 is newer, and 12 if EVR2
is newer.  Other exit statuses indicate problems.

firefox-88.0-8.fc34 > firefox-88.0.1-1.fc34
11 $ echo $?
11
```

I don't know whether this should be handled differently on the Firefox side or it's a bug in RPM (probably the former).

**Comment by cjao** [comment] 2021-05-14 10:48
Ok. Should I rename this to "system update results in Firefox downgrade" or open a new bug?

**Comment by tpopela** [comment] 2021-05-14 10:53
But what you are describing didn't happened.. Your Firefox was updated to the last release - look at the build in https://koji.fedoraproject.org/koji/packageinfo?packageID=37 . I will try to get in touch with someone from the RPM team, who can say where the problem is.

**Comment by sharkcz** [comment] 2021-05-14 11:23
You should be comparing versions as `rpmdev-vercmp 88.0-8.fc34 88.0.1-1.fc34` (omit the package name), which will confirm `88.0.1` is newer. It might be a bug in rpm-ostree.

**Comment by travier** [comment] 2021-05-14 11:28
This is most likely fixed by https://github.com/coreos/rpm-ostree/pull/2782 which will be included in the next rpm-ostree release

**Comment by tpopela** [comment] 2021-05-14 11:29
Ah, thank you @sharkcz and @travier ! Let me close this (as it's tracked in https://github.com/coreos/rpm-ostree/pull/2782)

**Closed by tpopela** 2021-05-14 11:29 UTC
