### ISSUE TITLE
GNOME Software doesn't update 'Secure Boot dbx Configuration Update'

### ISSUE THREAD

**Issue by Verhoeckx** [fedora-silverblue/issue-tracker#360] opened 2022-09-27 12:00 UTC
**Describe the bug**
When I click on the button Update in GNOME Software to update the device firmware 'Secure Boot dbx Configuration Update', the word 'Installing' is shown for a short second after which the text 'Update' is shown again.
<br>    
    
**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Open GNOME Software in Fedora Silverblue
2. Click on the button Update.
<br>

**Expected behavior**
I expect the 'Secure Boot dbx Configuration Update' to be updated.
<br>

**Screencast**
[Screencast from 09-27-2022 01:53:06 PM.webm](https://user-images.githubusercontent.com/64807887/192518278-6e155027-fdc9-4e0a-b251-016653aeec54.webm)
<br>

**Silverblue version:**
```
● fedora:fedora/36/x86_64/silverblue
                  Version: 36.20220927.0 (2022-09-27T00:44:16Z)
               BaseCommit: 3eda215e8345839a84c58e8a36660698492616f818ed6958864471875b653c8e
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
          LayeredPackages: containernetworking-plugins ffmpeg gnome-tweak-tool nautilus-dropbox rpmfusion-free-release rpmfusion-nonfree-release simple-scan thai-scalable-purisa-fonts vim xsane
            LocalPackages: Publii-0.40.2-1.x86_64 uld-1.00.39-1.fc34.x86_64
```
<br>

**Other**
If there is a command to manually fix this, please let me know!

**Comment by tpopela** [comment] 2022-09-27 12:19
This is a duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/120, see the https://github.com/fedora-silverblue/issue-tracker/issues/120#issuecomment-1177515110 for a manual fix.

**Comment by tpopela** [comment] 2022-09-27 12:20
Duplicate of #120

**Closed by tpopela** 2022-09-27 12:20 UTC
Labels: bug

**Comment by Verhoeckx** [comment] 2022-09-27 12:33
Okay, great to see that some people are working on it! Let me know If I need tot test something.
