### ISSUE TITLE
Fingerprint readers do not work out of the box, unlike Fedora 33 Workstation

### ISSUE THREAD

**Issue by dylanmtaylor** [fedora-silverblue/issue-tracker#101] opened 2020-11-12 14:38 UTC
The solution is to include fprintd, libfprintd and fprintd-pam packages by default.

running rpm-ostree install fprintd fprintd-pam fixes this issue.

**Comment by tpopela** [comment] 2020-11-12 17:28
Duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/62

**Closed by tpopela** 2020-11-12 17:28 UTC
