### ISSUE TITLE
[BUG] Unable to enter any toolbox containers `Failed to decode the keys ["storage.options.ostree_repo"]`

### ISSUE THREAD

**Issue by heyakyra** [fedora-silverblue/issue-tracker#213] opened 2021-10-01 03:43 UTC
**Describe the bug**
Unable to enter any toolbox containers after f34→f35 rebase

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Create a toolbox like:
```
toolbox create --container python --distro fedora --release 34
Image required to create toolbox container.
Download registry.fedoraproject.org/fedora-toolbox:34 (500MB)? [y/N]: y
Creating container python: | Created container: python
Enter with: toolbox enter python
```
2. Try to enter the toolbox
```
toolbox enter python
Error: invalid entry point PID of container python
```
3. check podman
```
$ podman images list
WARN[0000] Failed to decode the keys ["storage.options.ostree_repo"] from "/home/myname/.config/containers/storage.conf".
WARN[0000] Failed to decode the keys ["storage.options.ostree_repo"] from "/var/home/myname/.config/containers/storage.conf".
REPOSITORY  TAG         IMAGE ID    CREATED     SIZE
$ podman container list
WARN[0000] Failed to decode the keys ["storage.options.ostree_repo"] from "/home/myname/.config/containers/storage.conf".
WARN[0000] Failed to decode the keys ["storage.options.ostree_repo"] from "/var/home/myname/.config/containers/storage.conf".
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
```
4. Check that file
```
$ cat /home/myname/.config/containers/storage.conf
[storage]
  driver = "overlay"
  runroot = "/run/user/1000"
  graphroot = "/var/home/kyra/.local/share/containers/storage"
  [storage.options]
    size = ""
    remap-uids = ""
    remap-gids = ""
    remap-user = ""
    remap-group = ""
    ostree_repo = ""
    skip_mount_home = ""
    mount_program = "/usr/bin/fuse-overlayfs"
    mountopt = ""
    [storage.options.thinpool]
      autoextend_percent = ""
      autoextend_threshold = ""
      basesize = ""
      blocksize = ""
      directlvm_device = ""
      directlvm_device_force = ""
      fs = ""
      log_level = ""
      min_free_space = ""
      mkfsarg = ""
      mountopt = ""
      use_deferred_deletion = ""
      use_deferred_removal = ""
      xfs_nospace_max_retries = ""
```

**Expected behavior**
entering works

**OS version:**
```
$ rpm-ostree status -b
State: busy
Transaction: install python3-virtualenv
  Initiator: client(id:cli dbus:1.385 unit:app-gnome-alacritty-16797.scope uid:1000)
BootedDeployment:
● fedora:fedora/35/x86_64/silverblue
                   Version: 35.20210928.n.0 (2021-09-28T08:06:20Z)
                BaseCommit: 629901585d1c1b72fe48b2fc4b8f37e8f1f2398f08f13e749e66aa3f15ffa122
              GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F
           LayeredPackages: snapd nethogs setroubleshoot tmux baobab parallel gitk libicu-devel libvirt-devel gstreamer1-plugins-bad-freeworld scribus gnutls-devel libvirt moreutils java-1.8.0-openjdk
                            gnome-tweak-tool expect ncurses-devel apr-devel vagrant-libvirt ffmpeg help2man libapreq2-devel rpmfusion-free-release gstreamer-plugin-crystalhd gstreamer-plugins-bad-nonfree pbuilder
                            traceroute python-wxpython4 firewall-config ccache texlive-beamer fakeroot vlc gstreamer1-libav sushi java-latest-openjdk abrt-desktop gstreamer1-plugins-ugly rpmfusion-nonfree-release
                            git-cola pygtk2-devel samba code celluloid python3.6 hw-probe vim gstreamer-plugins-ugly libuuid-devel NetworkManager-l2tp-gnome rubygem-rexml python3.7 gstreamer1-plugin-openh264
                            texlive-latex-fonts python3.8 mosh python3-yaml socat pygtk2 python-devel kakoune virt-manager krb5-devel reptyr iotop gstreamer-ffmpeg OpenIPMI mariadb-connector-c-devel vagrant
                            debhelper gstreamer1-vaapi apt strongswan alsa-firmware gstreamer1-plugins-good-extras openh264 gstreamer1-plugins-fc gpaste udftools tmate OpenIPMI-tools texlive-logical-markup-utils
                            pavucontrol ipmitool yasm cargo tig tidy rubber texlive-gmutils moby-engine texlive-collection-latexextra NetworkManager-strongswan pitivi f2fs-tools texlive-ttfutils xorriso
                            PackageKit-gstreamer-plugin bind-dnssec-utils axel libattr-devel cabal-install alsa-tools google-chrome-unstable valgrind ruby-devel wireguard-tools tilix cmake gstreamer-plugins-bad
                            gstreamer1-plugins-bad-free-extras avahi-compat-libdns_sd-devel mariadb-connector-c net-tools autojump texlive-collection-fontsrecommended devscripts totem meld autossh
                            texlive-collection-fontsextra pam-devel gitg 'g++' ShellCheck epiphany perltidy rust mozilla-openh264 texlive-collection-fontutils pv crontabs krb5-server fuse-devel htop et screen
                            asciidoc docker-compose
             LocalPackages: zoom-5.8.0.16-1.x86_64
```

**Comment by tpopela** [comment] 2021-10-01 08:48
Duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/209

**Closed by tpopela** 2021-10-01 08:48 UTC

**Comment by heyakyra** [comment] 2021-10-01 14:11
Thanks. To save others a click to the upstream: https://github.com/containers/toolbox/issues/821

**Comment by juhp** [comment] 2021-10-02 06:21
(BTW the warnings, which are not related, will be gone I think if you remove the `storage.conf` file.)
