### ISSUE TITLE
[BUG]  Long time to confirmation dialog on reboot/shutdown/logout after ostree admin unlock

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#189] opened 2021-08-22 21:05 UTC
**Describe the bug**
( the bug appears only on unlocked deployments )
when you press the status area on the top right corner of the screen than choose any of those [ reboot, shutdown, logout ] it takes a very long time to show the confirmation dialog between 15s to 2 minutes ,
 **To Reproduce**
Please describe the steps needed to reproduce the bug:
1. ostree admin unlock --hotfix
2. reboot to boot entry 0
3. login than try to logout or reboot or shutdown from the ui

**Expected behavior**
a confirmation dialog appears immediately  

**OS version:**
```
Version: 34.20210817.0 (2021-08-17T00:48:48Z)
```

**Additional context**
it works perfectly on locked deployments

**Comment by TheOneandOnlyJakfrost** [comment] 2021-08-23 13:42
So, you unlocked your deployment, presumably to install snap, and then at logout, it takes longer to give you a prompt since the system now has to take stock of the changes or mutations applied at this current boot. Even if you haven't applied any, it will still check everything I'm sure. It works perfectly on unlocked deployments because the extra work wasn't introduced.

**Comment by travier** [comment] 2021-08-23 13:44
Please rename this issue to something more descriptive such as: `Long time to confirmation dialog on reboot/shutdown/logout after ostree admin unlock`.

Did you do anything else after `ostree admin unlock`?

**Comment by allaeddineomc** [comment] 2021-08-23 18:12
> So, you unlocked your deployment, presumably to install snap, and then at logout, it takes longer to give you a prompt since the system now has to take stock of the changes or mutations applied at this current boot. Even if you haven't applied any, it will still check everything I'm sure. It works perfectly on unlocked deployments because the extra work wasn't introduced.

the snap problem was on the desktop , this problem was on my laptop

**Comment by allaeddineomc** [comment] 2021-08-23 18:13
> Please rename this issue to something more descriptive such as: `Long time to confirmation dialog on reboot/shutdown/logout after ostree admin unlock`.
> 
> Did you do anything else after `ostree admin unlock`?

no

**Comment by tpopela** [comment] 2021-09-03 08:21
I can't reproduce it here on 34.20210830.0. I did `sudo ostree admin unlock` and tried the things from the top right menu and everything from there showed up instantly (even when I pressed the ctrl+alt+delete to show the dialog).

**Comment by allaeddineomc** [comment] 2021-09-03 16:42
> I can't reproduce it here on 34.20210830.0. I did `sudo ostree admin unlock` and tried the things from the top right menu and everything from there showed up instantly (even when I pressed the ctrl+alt+delete to show the dialog).

i reinstalled the system and the problem is gone

**Comment by shdwchn10** [comment] 2021-09-10 15:52
I have encountered with the same issue. But I didn't notice at what point it began to appear. I didn't run `sudo ostree admin unlock` never. I did `sudo rpm-ostree ex livefs --allow-replacement` and `sudo rpm-ostree install -A <package>` only.

**Comment by allaeddineomc** [comment] 2021-11-17 05:57
Anyone can confirm the bug is still present on f35 ?

**Comment by travier** [comment] 2022-08-19 22:28
Closing as we could not reproduce. Feel free to comment here if you still have this issue.

**Closed by travier** 2022-08-19 22:28 UTC
