### ISSUE TITLE
Bug: RPM packages prioritized over Flatpaks in GNOME Software

### ISSUE THREAD

**Issue by dschier-wtd** [fedora-silverblue/issue-tracker#368] opened 2022-10-13 10:12 UTC
**Describe the bug**

When using GNOME Software with Flathub, the "Linux Package" (RPM) is preferred over the Flatpak package. This is not a huge issue, since one can select the desired package format. Anyhow, as a new user, this seems unintuitive and also against the design of Silverblue. Flatpaks should be the preferred package format.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Install and Enable Flathub
2. Open GNOME Software
3. Select Geary and check the installation source (top right corner)

**Expected behavior**

The flatpak package is preferred

**Screenshots**

![image](https://user-images.githubusercontent.com/6490538/195569854-1cddccea-8d9e-4022-9f64-c8323d3462d3.png).

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/37/x86_64/silverblue
                  Version: 37.20221012.n.0 (2022-10-12T08:02:48Z)
               BaseCommit: 544c240a85ac556351e4fc9ff54a8d90154d4c34828723f280e68cc89e0bd405
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
      RemovedBasePackages: firefox firefox-langpacks 105.0.1-2.fc37 gnome-classic-session 43.0-1.fc37
~ 
```

**Additional context**

**Comment by tpopela** [comment] 2022-10-13 12:12
Duplicate of #354

**Closed by tpopela** 2022-10-13 12:12 UTC
Labels: bug
