### ISSUE TITLE
[BUG] rebase from F35 to F36 borks Gnome Software Center

### ISSUE THREAD

**Issue by vega-d** [fedora-silverblue/issue-tracker#269] opened 2022-05-10 11:40 UTC
**Describe the bug**
Attempting to use gnome software after a (otherwise successful) rebase from fc35 to fc36 results in gnome software being completely broken.
It fails to fetch new updates with `cannot create temporary file` error. Software catalog is empty, a reboot or a different (and surely working) internet connection did not solve the issue. 

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. have F35 install
2. rebase to F36
3. open gnome software and attempt to do a software update

**Expected behavior**
Well, a working software center I guess. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35414314/167619971-ff8c03a7-bb2d-44b1-95fe-fc8b7e8861d4.png)
![image](https://user-images.githubusercontent.com/35414314/167619981-01f5e045-4a6a-4bc2-9d43-6ce7e073b3f5.png)
![image](https://user-images.githubusercontent.com/35414314/167620012-d036f902-5485-4d21-a536-639de6cd8c44.png)
![image](https://user-images.githubusercontent.com/35414314/167620089-ab4b7c3a-5303-438c-a9bc-54c59d115d11.png)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220510.0 (2022-05-10T01:28:36Z)
                BaseCommit: 8e68c41bf30c73f76be8da7d1fd3be18d63ce33379ecf5c4267a5b42c20d9d74
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
       RemovedBasePackages: firefox 100.0-2.fc36
           LayeredPackages: fish freerdp gstreamer1-plugin-openh264 libvirt linux-enable-ir-emitter openssl virt-manager waydroid
             LocalPackages: howdy-2.6.1-5.fc35.x86_64
                 Initramfs: regenerate
```

**Additional context**
launching gnome-software from terminal to see the logs gave me this:
```
vega@dart ~ [SIGINT]> gnome-software
11:31:02:0140 Gs  /etc/PackageKit/Vendor.conf file not found
11:31:03:0088 libdnf Solv userdata length mismatch, read: 0 vs expected: 48
11:31:03:0092 Gs  failed to get popular apps: cannot create temporary file: /var/cache/rpm-ostree/solv/fedora-cisco-openh264.solv.x3Ge6q
11:31:03:0140 libdnf Solv userdata length mismatch, read: 0 vs expected: 48
11:31:03:0141 Gs  failed to get featured apps: cannot create temporary file: /var/cache/rpm-ostree/solv/fedora-cisco-openh264.solv.Ikx29m
11:31:03:0311 libdnf Solv userdata length mismatch, read: 0 vs expected: 48
11:31:03:0314 Gs  failed to get recent apps: cannot create temporary file: /var/cache/rpm-ostree/solv/fedora-cisco-openh264.solv.a8Ftel
11:31:03:0320 Gs  ignoring unknown or empty provided item type: font
11:31:03:0378 libdnf Solv userdata length mismatch, read: 0 vs expected: 48
11:31:03:0378 Gs  Failed to get system: Failed to refine '*/*/*/system/*': cannot create temporary file: /var/cache/rpm-ostree/solv/fedora-cisco-openh264.solv.IOqnX5
11:31:03:0415 Gs  ignoring unknown or empty provided item type: font
11:31:03:0415 Gs  ignoring unknown or empty provided item type: font
11:31:04:0410 libdnf Solv userdata length mismatch, read: 0 vs expected: 48
11:31:04:0425 Gs  failed to get installed apps: cannot create temporary file: /var/cache/rpm-ostree/solv/fedora-cisco-openh264.solv.OLOXOE
11:31:06:0416 libdnf Solv userdata length mismatch, read: 0 vs expected: 48
11:31:06:0416 Gs  updates-shell: failed to get updates: cannot create temporary file: /var/cache/rpm-ostree/solv/fedora-cisco-openh264.solv.h24kWD
```

**Comment by tpopela** [comment] 2022-05-10 17:01
Duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/257

**Closed by tpopela** 2022-05-10 17:01 UTC
