### ISSUE TITLE
x86_64 Silverblue installer build fails with errors trying to install flatpaks

### ISSUE THREAD

**Issue by AdamWill** [fedora-silverblue/issue-tracker#68] opened 2020-07-02 19:42 UTC
Build of the x86_64 Silverblue installer image has failed in the last few Rawhide composes, with errors like this:

    2020-07-02 06:29:45,571: Performing post-installation setup tasks
    Performing post-installation setup tasks
    2020-07-02 06:31:08,346: running /mnt/koji/compose/rawhide/Fedora-Rawhide-20200702.n.0/work/x86_64/Silverblue/lorax_templates/ostree-based-installer/lorax-configure-repo.tmpl
    running /mnt/koji/compose/rawhide/Fedora-Rawhide-20200702.n.0/work/x86_64/Silverblue/lorax_templates/ostree-based-installer/lorax-configure-repo.tmpl
    2020-07-02 06:31:08,365: running /mnt/koji/compose/rawhide/Fedora-Rawhide-20200702.n.0/work/x86_64/Silverblue/lorax_templates/ostree-based-installer/lorax-embed-repo.tmpl
    running /mnt/koji/compose/rawhide/Fedora-Rawhide-20200702.n.0/work/x86_64/Silverblue/lorax_templates/ostree-based-installer/lorax-embed-repo.tmpl
    2020-07-02 06:32:51,455: running /mnt/koji/compose/rawhide/Fedora-Rawhide-20200702.n.0/work/x86_64/Silverblue/lorax_templates/ostree-based-installer/lorax-embed-flatpaks.tmpl
    running /mnt/koji/compose/rawhide/Fedora-Rawhide-20200702.n.0/work/x86_64/Silverblue/lorax_templates/ostree-based-installer/lorax-embed-flatpaks.tmpl
    2020-07-02 06:32:51,834: command output:
    Looking for matches?
    error: Cannot autolaunch D-Bus without X11 $DISPLAY

    command output:
    Looking for matches?
    error: Cannot autolaunch D-Bus without X11 $DISPLAY

    2020-07-02 06:32:51,834: command returned failure (1)
    command returned failure (1)
    2020-07-02 06:32:51,834: template command error in /mnt/koji/compose/rawhide/Fedora-Rawhide-20200702.n.0/work/x86_64/Silverblue/lorax_templates/ostree-based-installer/lorax-embed-flatpaks.tmpl:
    template command error in /mnt/koji/compose/rawhide/Fedora-Rawhide-20200702.n.0/work/x86_64/Silverblue/lorax_templates/ostree-based-installer/lorax-embed-flatpaks.tmpl:
    2020-07-02 06:32:51,834:   runcmd flatpak install -y --user fedora runtime/org.fedoraproject.Platform/x86_64/f32 app/org.gnome.Baobab/x86_64/stable app/org.gnome.Calculator/x86_64/stable app/org.gnome.Calendar/x86_64/stable app/org.gnome.Characters/x86_64/stable app/org.gnome.clocks/x86_64/stable app/org.gnome.Contacts/x86_64/stable app/org.gnome.eog/x86_64/stable app/org.gnome.Evince/x86_64/stable app/org.gnome.FileRoller/x86_64/stable app/org.gnome.font-viewer/x86_64/stable app/org.gnome.gedit/x86_64/stable app/org.gnome.Logs/x86_64/stable app/org.gnome.NautilusPreviewer/x86_64/stable app/org.gnome.Maps/x86_64/stable app/org.gnome.Screenshot/x86_64/stable app/org.gnome.Weather/x86_64/stable
      runcmd flatpak install -y --user fedora runtime/org.fedoraproject.Platform/x86_64/f32 app/org.gnome.Baobab/x86_64/stable app/org.gnome.Calculator/x86_64/stable app/org.gnome.Calendar/x86_64/stable app/org.gnome.Characters/x86_64/stable app/org.gnome.clocks/x86_64/stable app/org.gnome.Contacts/x86_64/stable app/org.gnome.eog/x86_64/stable app/org.gnome.Evince/x86_64/stable app/org.gnome.FileRoller/x86_64/stable app/org.gnome.font-viewer/x86_64/stable app/org.gnome.gedit/x86_64/stable app/org.gnome.Logs/x86_64/stable app/org.gnome.NautilusPreviewer/x86_64/stable app/org.gnome.Maps/x86_64/stable app/org.gnome.Screenshot/x86_64/stable app/org.gnome.Weather/x86_64/stable
    2020-07-02 06:32:51,835:   subprocess.CalledProcessError: Command '['flatpak', 'install', '-y', '--user', 'fedora', 'runtime/org.fedoraproject.Platform/x86_64/f32', 'app/org.gnome.Baobab/x86_64/stable', 'app/org.gnome.Calculator/x86_64/stable', 'app/org.gnome.Calendar/x86_64/stable', 'app/org.gnome.Characters/x86_64/stable', 'app/org.gnome.clocks/x86_64/stable', 'app/org.gnome.Contacts/x86_64/stable', 'app/org.gnome.eog/x86_64/stable', 'app/org.gnome.Evince/x86_64/stable', 'app/org.gnome.FileRoller/x86_64/stable', 'app/org.gnome.font-viewer/x86_64/stable', 'app/org.gnome.gedit/x86_64/stable', 'app/org.gnome.Logs/x86_64/stable', 'app/org.gnome.NautilusPreviewer/x86_64/stable', 'app/org.gnome.Maps/x86_64/stable', 'app/org.gnome.Screenshot/x86_64/stable', 'app/org.gnome.Weather/x86_64/stable']' returned non-zero exit status 1.
      subprocess.CalledProcessError: Command '['flatpak', 'install', '-y', '--user', 'fedora', 'runtime/org.fedoraproject.Platform/x86_64/f32', 'app/org.gnome.Baobab/x86_64/stable', 'app/org.gnome.Calculator/x86_64/stable', 'app/org.gnome.Calendar/x86_64/stable', 'app/org.gnome.Characters/x86_64/stable', 'app/org.gnome.clocks/x86_64/stable', 'app/org.gnome.Contacts/x86_64/stable', 'app/org.gnome.eog/x86_64/stable', 'app/org.gnome.Evince/x86_64/stable', 'app/org.gnome.FileRoller/x86_64/stable', 'app/org.gnome.font-viewer/x86_64/stable', 'app/org.gnome.gedit/x86_64/stable', 'app/org.gnome.Logs/x86_64/stable', 'app/org.gnome.NautilusPreviewer/x86_64/stable', 'app/org.gnome.Maps/x86_64/stable', 'app/org.gnome.Screenshot/x86_64/stable', 'app/org.gnome.Weather/x86_64/stable']' returned non-zero exit status 1.

see e.g. [the Fedora-Rawhide-20200702.n.0 task](https://koji.fedoraproject.org/koji/taskinfo?taskID=46450778), [20200701.n.0 task](https://koji.fedoraproject.org/koji/taskinfo?taskID=46411593) and [20200630.n.0 task](https://koji.fedoraproject.org/koji/taskinfo?taskID=46368239).

It seems to be [working OK on ppc64le](https://koji.fedoraproject.org/koji/taskinfo?taskID=46450777), which is interesting.

**Comment by AdamWill** [comment] 2020-07-14 16:32
https://pagure.io/fedora-lorax-templates/pull-request/47 is the fix for this, apparently.

**Comment by cmurf** [comment] 2020-07-14 16:40
> https://pagure.io/fedora-lorax-templates/pull-request/47 is the fix for this, apparently.

It is intended to fix the problem, we'll need to check after it gets merged and then after the next compose window to know for sure. Also, ppc64le and aarch64 aren't embedding flatpaks in the images, hence the problem isn't happening there.

**Comment by tpopela** [comment] 2020-08-12 07:38
This is fixed.

**Closed by tpopela** 2020-08-12 07:38 UTC
