### ISSUE TITLE
SIlverblue Boot Media/Installation .ISO File to include full GNOME environnement with new Anaconda Web UI

### ISSUE THREAD

**Issue by mahdiaqallal** [fedora-silverblue/issue-tracker#560] opened 2024-05-08 13:22 UTC
Silverblue installation process from a Boot Media (USB) or from an .ISO file installer, starts GRUB and leads almost directly to the Anaconda installer
**While usage of Anaconda reaches a dead-end  or needs to be exited, only a full hard reboot is available.
There is no network access, no CLI or GUI features meaning no access to offline (man pages) or online documentation**
(see screenshots)
![Screenshot from 2024-05-08 13-47-24](https://github.com/fedora-silverblue/issue-tracker/assets/93226923/a6354316-c9f1-4f46-ac8c-fddaea773602)
![Screenshot from 2024-05-08 13-47-41](https://github.com/fedora-silverblue/issue-tracker/assets/93226923/0906d081-b582-4ab5-b578-23351156f86a)
**It would be preferable that Silverblue installation process would lead after GRUB to a full GNOME environment akin Fedora Workstation Live :**
(see screenshots)
![Screenshot from 2024-05-09 15-17-14](https://github.com/fedora-silverblue/issue-tracker/assets/93226923/9cc4c40c-63bb-4675-8943-34b9ad69ba64)

- The latter has auto login from GDM and displays a "Welcome to Fedora !" window that leads to Anaconda
![Screenshot from 2024-05-09 14-58-02](https://github.com/fedora-silverblue/issue-tracker/assets/93226923/c0d5a1a2-9365-40ab-b948-0907cdc962eb)
- If needed GUI/CLI root access right can become available (sudo)

**In case the user needs to exit Anaconda, it reverts to GNOME without mandatory hard reboot
A GNOME  Workstation Live environment allows various GUI and CLI actions which are helpful during an installation** : 
run a Virtual Machine, Terminal Access, Text editors, browse Firefox for information, debugging, install applications, etc...

Anaconda Web UI is being re-developed into a new PatternFly-based UI has been developed. It is to become the Anaconda WebUI by default for Fedora Workstation [scheduled for Fedora Linux 41](https://fedoraproject.org/wiki/Changes/AnacondaWebUIforFedoraWorkstation). **Silverblue installation should benefit from this new Web UI** .

**Comment by travier** [comment] 2024-05-08 18:49
I think this is a duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/489

**Closed by travier** 2024-05-08 18:49 UTC
Labels: enhancement

**Comment by mahdiaqallal** [comment] 2024-05-08 19:48
Yes @travier you are quite right , I didn't catch similar [#489](https://github.com/fedora-silverblue/issue-tracker/issues/489)

Nevertheless, could you please elaborate why this enhancement won't be pursued ? Is my proposal irrelevant or outside Silverblue's roadmap or goals ?
