### ISSUE TITLE
GNOME Software: Fedora RPM version of app has screenshots broken

### ISSUE THREAD

**Issue by aral** [fedora-silverblue/issue-tracker#378] opened 2022-11-07 09:55 UTC
Not sure if this specific to this app or all RPM versions of apps but thought I’d capture it anyway.

**Describe the bug**

Same app, has screenshots in Flatpak version, screenshots are broken on RPM.

**To Reproduce**

1. Select the Marker app in GNOME Software
2. Select Fedora Linux (RPM) in the source drop-down

**Expected behavior**

Screenshots should appear.

**Actual behavior**

Screenshots are broken.

**Workaround**

Select the Flatpak version.

**Screenshots **

RPM:

![Screenshot from 2022-11-07 09-51-23](https://user-images.githubusercontent.com/41798/200280833-fc5f151d-5cd7-49fd-bf4d-b06ad72c463b.png)

Flatpak:

![image](https://user-images.githubusercontent.com/41798/200280756-6ff24ee6-4f25-4e21-8c5d-689fac7dc876.png)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/37/x86_64/silverblue
                  Version: 37.20221024.n.0 (2022-10-24T07:55:03Z)
               BaseCommit: 0784b1cfc32ee5cae4231a6313f1f329b77b00a72c1d90499f3d79a0cf8e45d3
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
          LayeredPackages: appeditor ffmpeg fish gnome-console gnome-tweak-tool
                           gstreamer1-plugin-openh264 gtk4-devel-tools langpacks-en
                           libvirt-daemon-config-network lm_sensors mozilla-openh264
                           rpmfusion-free-release rpmfusion-nonfree-release virt-install
```

**Additional context**

GNOME Software v43.

**Comment by mcrha** [comment] 2022-11-07 11:16
Looking into `/usr/share/app-info/xmls/fedora.xml.gz` the Marker has there three screenshots, (the first) referencing: https://raw.githubusercontent.com/fabiocolacio/Marker/master/scrot1.png . The GitHub returns 404 for it.

The Flathub version (see `/var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml`) references https://raw.githubusercontent.com/fabiocolacio/Marker/master/help/C/figures/scrot1.png , which is fine.

Funny enough, the change in the appstream data file had been done roughly 3 years ago:
https://github.com/fabiocolacio/Marker/blame/master/data/com.github.fabiocolacio.marker.appdata.xml

I do not see anything special in the rpm version: https://src.fedoraproject.org/rpms/marker/tree/rawhide

It looks like there's something fishy about the appstream-data package, using wrong screenshot URLs.

For example I see broken images with `Dictionary` RPM, but not with `Videos` (totem) RPM.

**Comment by mcrha** [comment] 2022-11-07 12:00
A little addition, the URLs for the screenshots had been fixed shortly after 2020.04.04 release [1], but since then there was done no release yet, thus the Fedora rpm uses the latest upstream release, which has incorrect screenshot references. An option is to backport the .appdata fix into the package, which would make this a packaging request.

I did not check what the problem is with the Dictionary package.

[1] https://github.com/fabiocolacio/Marker/commits/master/data/com.github.fabiocolacio.marker.appdata.xml

**Comment by travier** [comment] 2022-11-08 22:17
Nice find. We'll have to fix the package indeed.

**Comment by tpopela** [comment] 2022-11-09 08:11
I think that this should be reported to the Fedora maintainer by opening a bug against the component https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=marker and this issue closed as it's not Silverblue specific.

**Comment by travier** [comment] 2023-11-24 11:58
Is this still an issue on Fedora Silverblue 39? Thanks

**Comment by aral** [comment] 2023-11-28 14:35
@travier Can’t reproduce in 39. Please feel free to close.

**Comment by travier** [comment] 2023-11-29 10:24
Thanks for the update!

**Closed by travier** 2023-11-29 10:24 UTC
Labels: bug, good first issue, f37, upstream
