### ISSUE TITLE
Often time rpm-ostree gets killed automatically.

### ISSUE THREAD

**Issue by tazihad** [fedora-silverblue/issue-tracker#485] opened 2023-08-01 16:00 UTC
I have faced this issue multiple times. I don't know the cause. I have an old core i5 4th gen dual core laptop.
```
> rpm-ostree install akmod-nvidia xorg-x11-drv-nvidia-cuda distrobox ffmpeg-free libavcodec-freeworld libva-intel-driver neovim zsh
Checking out tree 4b7304a... done
Enabled rpm-md repositories: fedora-cisco-openh264 fedora-modular updates-modular updates fedora rpmfusion-free-updates rpmfusion-free rpmfusion-nonfree-updates rpmfusion-nonfree updates-archive
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2023-03-14T10:56:46Z solvables: 4
rpm-md repo 'fedora-modular' (cached); generated: 2023-04-13T20:30:47Z solvables: 1082
rpm-md repo 'updates-modular' (cached); generated: 2023-07-29T00:21:17Z solvables: 1082
rpm-md repo 'updates' (cached); generated: 2023-08-01T02:41:27Z solvables: 20008
rpm-md repo 'fedora' (cached); generated: 2023-04-13T20:37:10Z solvables: 69222
rpm-md repo 'rpmfusion-free-updates' (cached); generated: 2023-07-28T19:32:59Z solvables: 105
rpm-md repo 'rpmfusion-free' (cached); generated: 2023-04-14T11:37:11Z solvables: 468
rpm-md repo 'rpmfusion-nonfree-updates' (cached); generated: 2023-07-28T20:04:10Z solvables: 74
rpm-md repo 'rpmfusion-nonfree' (cached); generated: 2023-04-14T12:02:51Z solvables: 235
rpm-md repo 'updates-archive' (cached); generated: 2023-08-01T03:04:30Z solvables: 26797
Resolving dependencies... done
Will download: 123 packages (450.8 MB)
Downloading from 'fedora-cisco-openh264'... done
Downloading from 'rpmfusion-free'... done
Downloading from 'updates'... done
Downloading from 'fedora'... done
⠖ Downloading from 'rpmfusion-nonfree-updates'  18% [███░░░░░░░░░░░░░░░░░] (6m)                               Downloading from 'rpmfusion-nonfree-updates'... done
Downloading from 'rpmfusion-free-updates'... done
Importing packages... done
Checking out packages... done
Running pre scripts... done
error: Running %prein for akmods: bwrap(/bin/sh): Child process killed by signal 6; run `journalctl -t 'rpm-ostree(akmods.prein)'` for more information
```

And here's the `journalctl`
```
> journalctl -t 'rpm-ostree(akmods.prein)'
Aug 01 21:49:37 fedora rpm-ostree(akmods.prein)[17889]: groupadd.rpmostreesave: /etc/group.4: lock file alrea>
Aug 01 21:49:37 fedora rpm-ostree(akmods.prein)[17889]: groupadd.rpmostreesave: cannot lock /etc/group; try a>
Aug 01 21:49:37 fedora rpm-ostree(akmods.prein)[17916]: useradd.rpmostreesave: group 'akmods' does not exist
lines 1-3/3 (END)...skipping...
Aug 01 21:49:37 fedora rpm-ostree(akmods.prein)[17889]: groupadd.rpmostreesave: /etc/group.4: lock file already used (nlink: 1)
Aug 01 21:49:37 fedora rpm-ostree(akmods.prein)[17889]: groupadd.rpmostreesave: cannot lock /etc/group; try again later.
Aug 01 21:49:37 fedora rpm-ostree(akmods.prein)[17916]: useradd.rpmostreesave: group 'akmods' does not exist
```

**Comment by miabbott** [comment] 2023-08-01 17:25
> error: Running %prein for akmods: bwrap(/bin/sh): Child process killed by signal 6

This is an error that is coming from trying to install a driver via `akmods`. (Possibly a variant of https://github.com/fedora-silverblue/issue-tracker/issues/331?)

It looks like you are trying to install the NVidia drivers via `akmods-nvidia`; the docs for NVidia say to use `kmod-nvidia`

https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_using_nvidia_drivers

I would try using the suggested method to see if that improves your issue.

**Comment by tazihad** [comment] 2023-08-01 19:02
@miabbott Do I have to run `kmod` every time I update kernel? Or it's an automatic process like `akmod`?

**Comment by miabbott** [comment] 2023-08-01 20:51
No, the `rpm-ostree upgrade` process should handle any kmod stuff.

**Comment by travier** [comment] 2023-08-02 08:52
Closing as duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/331

**Closed by travier** 2023-08-02 08:52 UTC
Labels: bug
