### ISSUE TITLE
"sudo update-alternatives --config x-terminal-emulator" does not output anything.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [fedora-silverblue/issue-tracker#206] opened 2021-09-27 23:03 UTC
**Describe the bug**
`sudo update-alternatives --config x-terminal-emulator` does exit without displaying anything.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Execute `sudo update-alternatives --config x-terminal-emulator`.

**Expected behavior**
What is mentioned at http://osradar.com/wp-content/uploads/2018/12/term-2.png.
I shall not transcribe it.

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/rawhide/x86_64/silverblue
                   Version: Rawhide.20210926.n.0 (2021-09-26T06:06:58Z)
                BaseCommit: cd698aa61eed58010e7ece06f6d356486902baf8d3af2be4137d97ee15365f93
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
       RemovedBasePackages: gnome-tour 41~rc-1.fc36, gnome-connections 41.0-1.fc36, firefox 92.0-3.fc36
```

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2021-09-27 23:03
> This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

Unfortunately, I am not able to that currently. Thus, if anybody is able to quickly test it for me, I shall be very gratuitous.

**Comment by travier** [comment] 2021-09-28 22:57
alternatives are currently non functional on rpm-ostree based systems: https://github.com/coreos/fedora-coreos-tracker/issues/677. You can work around that by creating the symlinks manually.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2021-09-30 19:42
> http://github.com/fedora-silverblue/issue-tracker/issues/206#issuecomment-929683229.

Is configuring one issue to be closed when another is possible for Git? If so, I shall attempt to configure this one to, but you may be more sucessful.

**Comment by LorbusChris** [comment] 2021-10-01 00:17
related: https://github.com/fedora-sysv/chkconfig/issues/9

**Comment by tpopela** [comment] 2021-11-02 15:37
Duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/89

**Closed by tpopela** 2021-11-02 15:37 UTC
