### ISSUE TITLE
GRUB errors out on boot due to TPM module errors

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#353] opened 2022-09-18 07:38 UTC
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in [Red Hat Bugzilla](https://bugzilla.redhat.com/) (see [How to file a bug](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/)) or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
grub errors out on boot with a tpm error after yesterday's update for f37 , the error was present for some time in f35

**To Reproduce**
rpm-ostree update
reboot

**Expected behavior**
boots with no errors

**Screenshots**

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/37/x86_64/silverblue
                  Version: 37.20220917.n.0 (2022-09-17T08:40:50Z)
               BaseCommit: b8c2ee6d796392558966f93a665c46fc681bf0033660234d166556c8c7641170
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A

```

**Additional context**
a quick workaround (not really a solution) :
on boot keep smashing up or down arrows for the grub menu to show
press "c"
type these commands
rmmode tpm
normal
the menu will show again but now it will boot properly

**Comment by allaeddineomc** [comment] 2022-09-18 20:50
today's update updated grub , the issue is still present

**Comment by travier** [comment] 2022-09-19 10:56
This is likely an upstream GRUB bug or a firmware bug. Please file it in Bugzilla.

**Comment by allaeddineomc** [comment] 2022-09-19 14:21
can't access my fedora account anymore , please someone else report it

**Comment by travier** [comment] 2022-09-19 15:00
It's likely specific to your hardware so I would recommend that you create a new account to report it.

**Comment by allaeddineomc** [comment] 2022-09-20 18:14
bug reported on bugzilla 
https://bugzilla.redhat.com/show_bug.cgi?id=2128485 
i guess this issue can be closed here

**Comment by travier** [comment] 2022-09-21 11:03
Closing as the next steps will happen in Bugzilla.

**Comment by travier** [comment] 2023-03-27 17:36
Error message to help with searches:

```
../../grub-core/commands/efi/tpm.c:148:Unknown TPM error.
```

**Comment by rickatnight11** [comment] 2023-03-27 17:55
The Bugzilla issue got closed incorrectly as a kernel fix, so not sure what the next steps here are for an actual fix.

**Comment by travier** [comment] 2023-03-28 08:53
Note that this is marked "fixed" in F38.

**Comment by rickatnight11** [comment] 2023-03-28 10:58
Thanks, @travier!  I did comment on the BZ, which is still closed.  Where do you see this marked as fixed in F38?

**Comment by travier** [comment] 2023-03-29 09:32
https://bugzilla.redhat.com/show_bug.cgi?id=2128485#c9 mentions F37. DId you try with Fedora 38? Note that the bootloader is also not updated yet in Silverblue. See: https://github.com/fedora-silverblue/issue-tracker/issues/120

**Comment by jlaham** [comment] 2023-05-13 16:41
FWIW, still seeing this with f38.

```
State: idle
Deployments:
● fedora:fedora/38/x86_64/silverblue
                  Version: 38.20230513.0 (2023-05-13T00:46:58Z)
               BaseCommit: 0cb2293657eaba7b89c1c62d74fd69f6c7c42fe31b0df16fbae8708202377ab0
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
```

**Comment by travier** [comment] 2023-05-15 09:17
Note that this will likely not be fixed until we have https://github.com/fedora-silverblue/issue-tracker/issues/120.

Since that's on our end now, I'll re-open this issue.

**Comment by rickatnight11** [comment] 2023-07-12 22:05
I'm not sure why this blocks on implementing bootupd and removing ostree-grub2.  I believe this needs to be fixed in the tpm module in grub2 (I think it doesn't handle the older TPM on some Asus Zenbooks).  Can we get the related bugzilla re-opened?

**Comment by travier** [comment] 2023-07-15 12:02
If the bug is fixed in a newer GRUB version then we need bootloader updates. Silverblue systems don't update the bootloader right now which is why we need bootupd.

**Comment by rickatnight11** [comment] 2023-07-15 16:39
Ah, that makes sense for this issue tracker.  I've learned how to update the bootloader, myself, and new installs would at least benefit before bootupd is implemented.

It's not clear to me that the core grub issue is being tracked, though, since the [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2128485) was closed.  Are you able to reopen it?

**Comment by travier** [comment] 2023-07-17 13:51
Can you verify that this is still an issue from a fresh Fedora 38 installation and comment in the Bugzilla?

**Comment by rickatnight11** [comment] 2023-07-17 14:36
Yes, confirmed it's still an issue and commented on the bugzilla.

**Comment by travier** [comment] 2023-11-24 11:52
I think this is still an issue on F39 but if someone affected could confirm that would be great. Thanks

**Comment by rickatnight11** [comment] 2023-11-24 13:12
Can confirm, still on f39.

**Comment by travier** [comment] 2024-10-30 16:47
We now have bootupd in Fedora 41. Can someone try updating their systems, making sure that bootupd updated the bootloader (`systemctl status bootloader-update.service`), rebooting again to see if this is fixed? Thanks

**Comment by rickatnight11** [comment] 2024-10-31 22:28
I updated to Fedora 41 today, and I can confirm bootupd is in place:

```
# systemctl status bootloader-update
● bootloader-update.service - Update bootloader on boot
     Loaded: loaded (/usr/lib/systemd/system/bootloader-update.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (exited) since Thu 2024-10-31 18:08:28 EDT; 13min ago
 Invocation: 831ee811933a4734a2746e1d8de59b3e
       Docs: https://github.com/coreos/bootupd
    Process: 1066 ExecStart=/usr/bin/bootupctl update (code=exited, status=0/SUCCESS)
   Main PID: 1066 (code=exited, status=0/SUCCESS)
   Mem peak: 41M
        CPU: 262ms
 
Oct 31 18:08:27 rick-ux305f-fedora-sb systemd[1]: Starting bootloader-update.service - Update bootloader on boot...
Oct 31 18:08:28 rick-ux305f-fedora-sb bootupctl[1066]: Adopted and updated: EFI: grub2-efi-ia32-1:2.12-10.fc41.x86_64,grub2-efi-x64-1:2.12-10.fc41.x86_64,shim-ia32-15.8-3.x86_64,shim-x64-15.8-3.x86_64
Oct 31 18:08:28 rick-ux305f-fedora-sb systemd[1]: Finished bootloader-update.service - Update bootloader on boot.

 bootupctl status
Running as unit: bootupd.service
Component EFI
  Installed: grub2-efi-ia32-1:2.12-10.fc41.x86_64,grub2-efi-x64-1:2.12-10.fc41.x86_64,shim-ia32-15.8-3.x86_64,shim-x64-15.8-3.x86_64
  Update: At latest version
No components are adoptable.
Boot method: EFI
```

...however the `tpm` module issue still persists on boot.

I think this is because the bug [is in grub](https://bugzilla.redhat.com/show_bug.cgi?id=2128485), however the change to bootupd  means when/if a fix _does_ release, it'll actually get rolled out (whereas on ostree-grub2 was never updating the grub/EFI files after initial install.)

**Closed** 2024-11-05 11:22 UTC
Labels: bug, f39, f40
