### ISSUE TITLE
dual boot Fedora Workstation and Fedora Silverblue

### ISSUE THREAD

**Issue by cmurf** [fedora-silverblue/issue-tracker#131] opened 2021-02-27 08:09 UTC
anaconda bug when installing silverblue 34 after installing and setting up Fedora Workstation 34
https://bugzilla.redhat.com/show_bug.cgi?id=1930985

Details, logs, and screenshots are in the above bug, but these are the reproduce steps:

* install Fedora-Workstation-Live-x86_64-34-20210219.n.0.iso to a blank disk using Automatic partitioning
* reboot
* configure user
* shutdown
* boot Fedora-Silverblue-ostree-x86_64-34-20210219.n.0.iso
* Use Custom partitioning
* New Fedora installation, keep partitioning scheme on Btrfs
* Fedora Linux 34 for x86_64:
    * Click on /boot/efi, set Mount Point field to /boot/efi, click Update Settings [1]
    * Click on /boot, set Mount Point field to /boot, click Update Settings  [1]
    * Click on /home, set Mount Point field to /home, click Update Settings
* Lower left UI, click [+], enter / for the Mount Point, leave Desired Capacity Blank, click Add mount point [2]

**Comment by travier** [comment] 2022-08-21 13:44
Closing this one as a duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/284

**Closed by travier** 2022-08-21 13:44 UTC
