### ISSUE TITLE
[BUG] Silverblue 35 update did not resolve due to rpm-build package conflict

### ISSUE THREAD

**Issue by shoop** [fedora-silverblue/issue-tracker#233] opened 2022-01-21 10:56 UTC
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
Sorry I don't have a Workstation install ready to reproduce...

I got a notification for a system upgrade on Silverblue 35, however the transaction reported 4 errors.
From the command line output:

```
stijn@tangaloor: ~
$ sudo rpm-ostree upgrade
2 metadata, 0 content objects fetched; 788 B transferred in 0 seconds; 0 bytes content written
Checking out tree ce3c28c... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora rpmfusion-free-updates rpmfusion-free rpmfusion-nonfree-updates rpmfusion-nonfree phracek-PyCharm google-chrome rpmfusion-nonfree-nvidia-driver rpmfusion-nonfree-steam updates-archive
Updating metadata for 'fedora-cisco-openh264'... done
Updating metadata for 'updates'... done
Updating metadata for 'fedora'... done
Updating metadata for 'rpmfusion-free-updates'... done
Updating metadata for 'rpmfusion-free'... done
Updating metadata for 'rpmfusion-nonfree-updates'... done
Updating metadata for 'rpmfusion-nonfree'... done
Updating metadata for 'phracek-PyCharm'... done
Updating metadata for 'google-chrome'... done
Updating metadata for 'rpmfusion-nonfree-nvidia-driver'... done
Updating metadata for 'rpmfusion-nonfree-steam'... done
Updating metadata for 'updates-archive'... done
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264'; generated: 2021-09-21T18:07:30Z solvables: 4
rpm-md repo 'updates'; generated: 2022-01-20T14:40:25Z solvables: 17722
rpm-md repo 'fedora'; generated: 2021-10-26T05:31:27Z solvables: 65732
rpm-md repo 'rpmfusion-free-updates'; generated: 2022-01-09T22:33:28Z solvables: 127
rpm-md repo 'rpmfusion-free'; generated: 2021-10-23T21:56:55Z solvables: 521
rpm-md repo 'rpmfusion-nonfree-updates'; generated: 2022-01-09T23:12:45Z solvables: 49
rpm-md repo 'rpmfusion-nonfree'; generated: 2021-10-23T23:27:21Z solvables: 203
rpm-md repo 'phracek-PyCharm'; generated: 2022-01-19T10:20:58Z solvables: 5
rpm-md repo 'google-chrome'; generated: 2022-01-20T23:24:47Z solvables: 3
rpm-md repo 'rpmfusion-nonfree-nvidia-driver'; generated: 2022-01-12T14:47:40Z solvables: 29
rpm-md repo 'rpmfusion-nonfree-steam'; generated: 2021-12-24T13:52:43Z solvables: 2
rpm-md repo 'updates-archive'; generated: 2022-01-20T15:18:49Z solvables: 21480
Resolving dependencies... done
error: Could not depsolve transaction; 4 problems detected:
 Problem 1: conflicting requests
  - package akmod-nvidia-3:495.46-1.fc35.x86_64 requires akmods, but none of the providers can be installed
  - package akmod-nvidia-3:470.74-1.fc35.x86_64 requires akmods, but none of the providers can be installed
  - package akmods-0.5.6-28.fc35.noarch requires rpm-build, but none of the providers can be installed
  - package rpm-build-4.17.0-1.fc35.x86_64 requires rpm = 4.17.0-1.fc35, but none of the providers can be installed
  - cannot install both rpm-4.17.0-1.fc35.x86_64 and rpm-4.17.0-3.fc35.x86_64
 Problem 2: conflicting requests
  - package kmod-nvidia-3:495.46-1.fc35.x86_64 requires akmod-nvidia = 3:495.46-1.fc35, but none of the providers can be installed
  - package kmod-nvidia-3:470.74-1.fc35.x86_64 requires akmod-nvidia = 3:470.74-1.fc35, but none of the providers can be installed
  - package akmod-nvidia-3:495.46-1.fc35.x86_64 requires akmods, but none of the providers can be installed
  - package akmod-nvidia-3:470.74-1.fc35.x86_64 requires akmods, but none of the providers can be installed
  - package akmods-0.5.6-28.fc35.noarch requires rpm-build, but none of the providers can be installed
  - package rpm-build-4.17.0-1.fc35.x86_64 requires rpm = 4.17.0-1.fc35, but none of the providers can be installed
  - cannot install both rpm-4.17.0-1.fc35.x86_64 and rpm-4.17.0-3.fc35.x86_64
  - package rpm-libs-4.17.0-3.fc35.x86_64 requires rpm = 4.17.0-3.fc35, but none of the providers can be installed
 Problem 3: conflicting requests
  - package xorg-x11-drv-nvidia-3:495.46-1.fc35.x86_64 requires nvidia-kmod >= 3:495.46, but none of the providers can be installed
  - package xorg-x11-drv-nvidia-3:470.74-1.fc35.x86_64 requires nvidia-kmod >= 3:470.74, but none of the providers can be installed
  - package kmod-nvidia-3:495.46-1.fc35.x86_64 requires akmod-nvidia = 3:495.46-1.fc35, but none of the providers can be installed
  - package kmod-nvidia-3:470.74-1.fc35.x86_64 requires akmod-nvidia = 3:470.74-1.fc35, but none of the providers can be installed
  - package akmod-nvidia-3:495.46-1.fc35.x86_64 requires akmods, but none of the providers can be installed
  - package akmod-nvidia-3:470.74-1.fc35.x86_64 requires akmods, but none of the providers can be installed
  - package akmods-0.5.6-28.fc35.noarch requires rpm-build, but none of the providers can be installed
  - package rpm-build-4.17.0-1.fc35.x86_64 requires rpm = 4.17.0-1.fc35, but none of the providers can be installed
  - cannot install both rpm-4.17.0-1.fc35.x86_64 and rpm-4.17.0-3.fc35.x86_64
  - package rpm-libs-4.17.0-3.fc35.x86_64 requires rpm = 4.17.0-3.fc35, but none of the providers can be installed
  - package python3-rpm-4.17.0-3.fc35.x86_64 requires rpm-libs(x86-64) = 4.17.0-3.fc35, but none of the providers can be installed
 Problem 4: conflicting requests
  - package xorg-x11-drv-nvidia-cuda-3:495.46-1.fc35.x86_64 requires nvidia-kmod >= 3:495.46, but none of the providers can be installed
  - package xorg-x11-drv-nvidia-cuda-3:470.74-1.fc35.x86_64 requires nvidia-kmod >= 3:470.74, but none of the providers can be installed
  - package kmod-nvidia-3:495.46-1.fc35.x86_64 requires akmod-nvidia = 3:495.46-1.fc35, but none of the providers can be installed
  - package kmod-nvidia-3:470.74-1.fc35.x86_64 requires akmod-nvidia = 3:470.74-1.fc35, but none of the providers can be installed
  - package akmod-nvidia-3:495.46-1.fc35.x86_64 requires akmods, but none of the providers can be installed
  - package akmod-nvidia-3:470.74-1.fc35.x86_64 requires akmods, but none of the providers can be installed
  - package akmods-0.5.6-28.fc35.noarch requires rpm-build, but none of the providers can be installed
  - package rpm-build-4.17.0-1.fc35.x86_64 requires rpm = 4.17.0-1.fc35, but none of the providers can be installed
  - cannot install both rpm-4.17.0-1.fc35.x86_64 and rpm-4.17.0-3.fc35.x86_64
  - package rpm-libs-4.17.0-3.fc35.x86_64 requires rpm = 4.17.0-3.fc35, but none of the providers can be installed
  - package rpm-build-libs-4.17.0-3.fc35.x86_64 requires rpm-libs(x86-64) = 4.17.0-3.fc35, but none of the providers can be installed
```

Note that this includes nvidia-driver packages, but these are not related to the root cause. Whittling this down it turned out to be that the proposed upgrade had `rpm-build-4.17.0.1-fc35.x86_64` and the transaction wanted to install `rpm-4.17.0-3.fc35.x86_64`.

What I don't understand is that the binary `rpm-build` package is a subpackage of the `rpm` source package. So how is it possible that I have a transaction that does not upgrade rpm-build but wants to update rpm ?

State of the system at time of error:

```
stijn@tangaloor: ~
$ sudo rpm-ostree status
State: idle
Deployments:
● fedora:fedora/35/x86_64/silverblue
				   Version: 35.20220106.0 (2022-01-06T00:43:14Z)
				BaseCommit: eb0ceda40ffd5f55c721306484cb2e6689293e17ecc8681be503edd1d4f002d6
			  GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F
	   RemovedBasePackages: firefox 95.0.2-2.fc35
		   LayeredPackages: akmod-nvidia kmod-nvidia tmux vim xorg-x11-drv-nvidia xorg-x11-drv-nvidia-cuda ykpers
			 LocalPackages: brother-hl-l8250cdn-1.0-1.fc35.x86_64 rpmfusion-free-release-35-1.noarch rpmfusion-nonfree-release-35-1.noarch

  fedora:fedora/35/x86_64/silverblue
				   Version: 35.20220106.0 (2022-01-06T00:43:14Z)
				BaseCommit: eb0ceda40ffd5f55c721306484cb2e6689293e17ecc8681be503edd1d4f002d6
			  GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F
	   RemovedBasePackages: firefox 95.0.2-2.fc35
		   LayeredPackages: kmod-nvidia tmux vim xorg-x11-drv-nvidia xorg-x11-drv-nvidia-cuda ykpers
			 LocalPackages: brother-hl-l8250cdn-1.0-1.fc35.x86_64 rpmfusion-free-release-35-1.noarch rpmfusion-nonfree-release-35-1.noarch
```

I fixed this by doing the following sequence:

1. Deinstall the layered nvidia-packages that depend on akmods that depends on rpm-build, then reboot
2. Download `rpm-build-4.17.0-3.fc35.x86_64.rpm` from [Koji](https://koji.fedoraproject.org/koji/buildinfo?buildID=1877989), install it using `rpm-ostree install`, reboot
3. Upgrade system using `rpm-ostree upgrade`, reboot
4. Reinstall nvidia-packages, reboot

**To Reproduce**
Not sure if I still can.

**Expected behavior**
Both binary packages of the same source build included in a single transaction.

**Screenshots**
n/a see above for terminal output.

**OS version:**
```
$ rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/35/x86_64/silverblue
                   Version: 35.20220121.0 (2022-01-21T03:09:39Z)
                BaseCommit: ce3c28c17f6f1fe24268780117536ed33e7b7f6a7d24dc8dff4d5899da2c05ae
              GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F
       RemovedBasePackages: firefox 96.0-1.fc35
           LayeredPackages: akmod-nvidia kmod-nvidia tmux vim xorg-x11-drv-nvidia
                            xorg-x11-drv-nvidia-cuda ykpers
             LocalPackages: brother-hl-l8250cdn-1.0-1.fc35.x86_64
                            rpm-build-4.17.0-3.fc35.x86_64
                            rpmfusion-free-release-35-1.noarch
                            rpmfusion-nonfree-release-35-1.noarch
```

**Additional context**
New to Silverblue, feel free to let me know if I did anything stupid and/or should lower expectations.

**Comment by travier** [comment] 2022-01-21 11:01
Might be a temporary issue.

See also https://discussion.fedoraproject.org/t/simplifying-updates-for-rpm-fusion-packages-and-other-packages-shipping-their-own-rpm-repos/30364?u=siosm for an unrelated issue that you want to to do for rpmfusion repo packages.

**Comment by shoop** [comment] 2022-01-21 11:07
hi @travier, thanks for the pointer, I'll check it out.

I would have thought the same (temporary issue) when on Workstation. But the main draw of Silverblue for me was the atomic upgrades. Note that `rpm-build` has nothing to do with the rpm-fusion packages, so my expectation is that it was in the core image. Is that expectation incorrect?

**Comment by travier** [comment] 2022-01-21 13:12
This the atomic part of rpm-ostree upgrades working as intended: you don't end up with a broken system and you can resolve package conflicts beforehand, with no risk.

In this case, I don't know why you had conflicts here and on my Silverblue system, both `rpm` & `rpm-build` have been updated thus I am suspecting an interaction with the nvidia driver here.

The rpmfusion link I added is just a bonus for you for when you rebase to Fedora 36. It should not be related to your issue here.

**Comment by gblach** [comment] 2022-01-21 14:15
I have a similar issue, but in my case it is related to another kmod

$ rpm-ostree upgrade
2 metadata, 0 content objects fetched; 788 B transferred in 2 seconds; 0 bytes content written
Checking out tree ce3c28c... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora rpmfusion-free-updates rpmfusion-free rpmfusion-nonfree-updates rpmfusion-nonfree google-chrome updates-archive
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2021-09-21T18:07:30Z solvables: 4
rpm-md repo 'updates' (cached); generated: 2022-01-20T14:40:25Z solvables: 17722
rpm-md repo 'fedora' (cached); generated: 2021-10-26T05:31:27Z solvables: 65732
rpm-md repo 'rpmfusion-free-updates' (cached); generated: 2022-01-09T22:33:28Z solvables: 127
rpm-md repo 'rpmfusion-free' (cached); generated: 2021-10-23T21:56:55Z solvables: 521
rpm-md repo 'rpmfusion-nonfree-updates' (cached); generated: 2022-01-09T23:12:45Z solvables: 49
rpm-md repo 'rpmfusion-nonfree' (cached); generated: 2021-10-23T23:27:21Z solvables: 203
rpm-md repo 'google-chrome' (cached); generated: 2022-01-20T23:24:47Z solvables: 3
rpm-md repo 'updates-archive' (cached); generated: 2022-01-20T15:18:49Z solvables: 21480
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: package akmods-0.5.6-28.fc35.noarch requires rpm-build, but none of the providers can be installed
  - package rpm-build-4.17.0-1.fc35.x86_64 requires rpm = 4.17.0-1.fc35, but none of the providers can be installed
  - package akmod-wl-6.30.223.271-39.fc35.x86_64 requires akmods, but none of the providers can be installed
  - cannot install both rpm-4.17.0-1.fc35.x86_64 and rpm-4.17.0-3.fc35.x86_64
  - package kmod-wl-6.30.223.271-39.fc35.x86_64 requires akmod-wl = 6.30.223.271-39.fc35, but none of the providers can be installed
  - conflicting requests

**Comment by travier** [comment] 2022-08-19 22:20
Closing as this is likely resolved now. Feel free to comment if that's not the case.

**Closed by travier** 2022-08-19 22:20 UTC
