### ISSUE TITLE
[BUG] Missing fonts in "Preferences" page of Text Editor Flatpak

### ISSUE THREAD

**Issue by user1-github** [fedora-silverblue/issue-tracker#299] opened 2022-06-22 19:28 UTC
**Describe the bug**
The Flatpak version of Text Editor has missing fonts in "Preferences" page. This issue is not present in Text Editor in Fedora Workstation 36 because it uses the rpm package. I already reported the issue in the Text Editor gitlab, but the developer said that they don't have control over fonts and it's not an issue with the app itself. So I report it here, since it's preinstalled in Silverblue.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Open the "Preferences" page in Text Editor Flatpak.
2. You'll see that Fonts are missing as shown in the screenshot.

**Expected behavior**
Fonts should work properly in the "Preferences" page.

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220617.0 (2022-06-17T00:45:03Z)
                    Commit: 5bf39cb84b31d36af49e07dfb57a5c531ad7c13a8b2df91397494bea9bf6e871
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
```

Edit: I found someone reported the same issue on [redhat bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2098088). Should I leave this issue open? Because I don't know who is responsible for the Fedora Flatpak version of Text Editor.

![Screenshot from 2022-06-22 19-43-29](https://user-images.githubusercontent.com/56021366/175120453-984bc7ed-b70d-49c5-9d5d-03bfdf47ed2e.png)

**Comment by 1player** [comment] 2022-06-27 08:23
I opened that bug report. Yeah, use the Flathub version instead.

**Comment by AdamWill** [comment] 2022-06-28 22:22
Yeah, openQA is hitting this too...

**Comment by juhp** [comment] 2022-06-29 04:53
Maybe the correct place to report this is https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora%20Modules ?
I suppose it is not Silverblue specific.

**Comment by AdamWill** [comment] 2022-06-29 15:15
Modules aren't flatpaks, they're https://docs.pagure.org/modularity/ . I don't actually know where is supposed to be The Right Place to report flatpak-specific issues. I picked here too, at least for ones that are default installed in Silverblue.

**Comment by tpopela** [comment] 2022-06-30 06:07
At least for now this issue tracker is indeed a better place for problems related preinstalled Fedora Flatpaks on Silverblue. Hmm this bug looks like a missing font or a non-existing font is set as the default one.

**Comment by tpopela** [comment] 2022-06-30 06:08
I see it here as well (when I turn off the "Custom Font" option that I have active)

**Comment by m911t** [comment] 2022-07-31 18:01
This also affects sushi, the previewer that appears when you press space with a file selected on the Files app

**Comment by 1player** [comment] 2022-08-01 09:28
> This also affects sushi, the previewer that appears when you press space with a file selected on the Files app

Off topic: I didn't know about Sushi, just tried it to preview a Libreoffice document, my desktop froze completely. Yikes. Not sure if it's related to the missing fonts, or it's something else. I don't care to try again.

**Comment by m911t** [comment] 2022-10-11 07:12
for the libreoffice thing: this happens on every distro that doesn't have libreoffice installed. installing the flatpak.doesnt solve it either. to avoid the freezing, use flatseal to remove the dbus permission from sushi.

also: i have my own fontconfig files on .config. giving all flatpaks access to .config/fontconfig fixes the missing fonts issue

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by AdamWill** [comment] 2022-10-11 08:38
Still valid for me, in all openQA tests of Fedora 37 and Rawhide. See https://openqa.fedoraproject.org/tests/1498835#step/skins/9 for the failure on today's Rawhide.

**Comment by 1player** [comment] 2022-10-11 08:49
Right, sorry. I could not reproduce because I've been using the Flathub version since this bug was reported. My bad.

**Comment by giomke** [comment] 2022-10-25 05:57
> **Describe the bug** The Flatpak version of Text Editor has missing fonts in "Preferences" page. This issue is not present in Text Editor in Fedora Workstation 36 because it uses the rpm package. I already reported the issue in the Text Editor gitlab, but the developer said that they don't have control over fonts and it's not an issue with the app itself. So I report it here, since it's preinstalled in Silverblue.
> 
> **To Reproduce** Please describe the steps needed to reproduce the bug:
> 
>     1. Open the "Preferences" page in Text Editor Flatpak.
> 
>     2. You'll see that Fonts are missing as shown in the screenshot.
> 
> 
> **Expected behavior** Fonts should work properly in the "Preferences" page.
> 
> **OS version:**
> 
> ```
> State: idle
> BootedDeployment:
> ● fedora:fedora/36/x86_64/silverblue
>                    Version: 36.20220617.0 (2022-06-17T00:45:03Z)
>                     Commit: 5bf39cb84b31d36af49e07dfb57a5c531ad7c13a8b2df91397494bea9bf6e871
>               GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
> ```
> 
> Edit: I found someone reported the same issue on [redhat bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2098088). Should I leave this issue open? Because I don't know who is responsible for the Fedora Flatpak version of Text Editor.
> 
> ![Screenshot from 2022-06-22 19-43-29](https://user-images.githubusercontent.com/56021366/175120453-984bc7ed-b70d-49c5-9d5d-03bfdf47ed2e.png)

## To Fix
1. Add flathub repository

```sh
$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```
2. Remove Text Editor from Software app
3. Reinstall Text Editor from flathub repo
![Screenshot from 2022-10-25 09-57-13](https://user-images.githubusercontent.com/19889044/197694060-09709f48-3cdd-4af3-bae7-3fac36e528ea.png)

**Comment by tagoh** [comment] 2022-10-25 11:31
The root cause is the same to https://github.com/fedora-silverblue/issue-tracker/issues/305 and it has already been fixed in fontconffig 2.14.1. we need to update the runtime for flatpaks.

For more details, gnome-text-editor tries to find out Monospace font but:
```
(gnome-text-editor:2): Pango-WARNING **: 20:12:41.626: failed to create cairo scaled font, expect ugly output. the offending font is 'Noto Sans Mono 11'

(gnome-text-editor:2): Pango-WARNING **: 20:12:41.626: font_face status is: file not found

(gnome-text-editor:2): Pango-WARNING **: 20:12:41.626: scaled_font status is: file not found
```
No Noto Sans Mono isn't installed which assigned to monospace. see:
```
$ fc-match -v --brief monospace:lang=en file
Pattern has 1 elts (size 16)
        file: "/usr/share/fonts/google-noto-vf/NotoSansMono-VF.ttf"(s)
```
but that place is actually where host has.
```
$ stat /usr/share/fonts/google-noto-vf/NotoSansMono-VF.ttf
stat: cannot statx '/usr/share/fonts/google-noto-vf/NotoSansMono-VF.ttf': No such file o
r directory
```
the cache must points to /run/host/fonts/google-noto-vf/NotoSansMono-VF.ttf instead.

**Comment by tagoh** [comment] 2022-10-25 11:44
Or maybe good to have NotoSansMono installed in flatpak runtime as well as a workaround for #305  if flatpak apps is possibly brought up from host where have no monospace fonts installed at all.

**Comment by tagoh** [comment] 2022-10-25 12:11
Oh I have to point out another one. we expect that /etc/fonts/conf.d/50-flatpak.conf would contains all the needed fontconfig config for flatpak specific but it doesn't contain any remap-dir elements which is supposed to bridge fonts directories from host to container.
I can see that in /run/host/font-dirs.xml but it isn't loaded from activated config at /etc/fonts.

**Comment by tagoh** [comment] 2022-10-25 12:29
Oh wait, I may found another bug in fontconfig. need more time to explain correct wording...

**Comment by tagoh** [comment] 2022-10-25 13:02
Actually there are two caches for /usr/share/fonts. one is available in the runtime. another one is bridged from host through /run/host/fonts.
fontconfig take care of caches by hash and hash is decided by font path. both caches for /usr/share/fonts and /run/host/fonts has same hash but different contents.
fontconig ignores duplicate caches and give a priority to the cache which found first. thus, if they have different font sets installed there, which one is available or not depends on the order of directories to read in config.

For this issue, we could work around if `<remap-dir as-path="/usr/share/fonts">/run/host/fonts</remap-dir>` appears faster than `<dir>/usr/share/fonts</dir>`, that will looks working. though apps won't be able to find any fonts out which is available only on /usr/share/fonts at the container. that is a side-effect.

I'll try to think about how I can fix but the cache system in fontconfig may needs to rework completely.

**Comment by AdamWill** [comment] 2023-02-24 00:46
This was fixed for a while, but came back in Fedora-Rawhide-20230202.n.1, probably due to the change from google-noto-fonts-20201206^1.git0c78c8329-10.fc38 to google-noto-fonts-20230201-1.fc38 , with the same root cause as https://github.com/fedora-silverblue/issue-tracker/issues/305 .

**Comment by travier** [comment] 2023-05-15 15:28
@AdamWill Is this still an issue?

**Comment by AdamWill** [comment] 2023-05-15 16:02
No, indeed, the fixes for https://github.com/fedora-silverblue/issue-tracker/issues/305 fixed this too.

**Comment by travier** [comment] 2023-05-15 16:03
Thanks!

**Closed by travier** 2023-05-15 16:03 UTC
Labels: bug, rawhide, flatpak
