### ISSUE TITLE
Incorrect keymap after installation, making it impossible to decrypt disks

### ISSUE THREAD

**Issue by toreanderson** [fedora-silverblue/issue-tracker#61] opened 2020-05-21 22:07 UTC
After installing Silverblue 32 from the ISO image, the keymap resets to U.S. English after the reboot.

When disk encryption is enabled, this is likely makes the installation unusable because the unlock passphrase gets rejected. The incorrect keymap mangles it before it gets passed on to `cryptsetup`. Furthermore, because the typed characters does not get echoed back to the user, it is almost impossible for the user to tell why it fails.

After numerous frustrating failures at installing Silverblue, I concluded that this is indeed what was happening by using a very simple passphrase: `zxcvb-`

The passphrase I had to input in order to successfully boot the system was a different one: `zxcvb+`

The reason why that worked is that the `+` key on my Norwegian keyboard is located immediately to the right of `0` key. That is also where the the `-` key would be located on an U.S. English keyboard. Therefore, when I pressed the `+` key, it registered as a `-` character.

**Comment by tpopela** [comment] 2020-05-25 08:57
This is a duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/3

**Closed by tpopela** 2020-05-25 08:57 UTC
