### ISSUE TITLE
[BUG] broken release candidate of podman in stable repo

### ISSUE THREAD

**Issue by Ma3yTa** [fedora-silverblue/issue-tracker#168] opened 2021-05-08 05:45 UTC
https://bodhi.fedoraproject.org/updates/FEDORA-2021-fc15685f73
https://github.com/containers/podman/issues/10274
Please unlist it.

**Comment by Ma3yTa** [comment] 2021-05-10 02:29
![image](https://user-images.githubusercontent.com/660379/117598523-fb17c280-b115-11eb-94a2-0b86e986be75.png)

**Comment by tpopela** [comment] 2021-05-10 09:36
Duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/166

**Closed by tpopela** 2021-05-10 09:36 UTC

**Comment by Ma3yTa** [comment] 2021-05-10 12:55
@tpopela the problem is how it is possible that a broken package like podman has been published to a stable repository. If I understand correctly Fedora Silverblue is not following a rolling release cycle. And still, the broken release candidate of podman is in a stable repository already 2 days.

**Comment by tpopela** [comment] 2021-05-10 13:01
@Ma3yTa because it got enough positive karma and the maintainers (rhcontainerbot) pushed it through - https://bodhi.fedoraproject.org/updates/FEDORA-2021-fc15685f73 (but you are already aware because you commented there). We currently don't have a way to prevent these. I talked to Rishi the Toolbox maintainer today and he said that there there is a test case in upstream podman to catch this particular breakage, but the test was skipped. He will look into why it's skipped and extend the test cases.

Sadly this is not a new issue and Toolbox is affected by nearly every podman update (you can look at the history in https://github.com/containers/toolbox/issues)

**Comment by Ma3yTa** [comment] 2021-05-10 13:02
@tpopela understand. thanks for the explanation.
