### ISSUE TITLE
No update since 38.20230624.0 (was: Conflict installing Samba)

### ISSUE THREAD

**Issue by JamesBelchamber** [fedora-silverblue/issue-tracker#475] opened 2023-06-27 07:58 UTC
Installing the samba package on Silverblue 38 reports a conflicting request:

```
$ rpm-ostree install samba
Checking out tree bad46f3... done
Enabled rpm-md repositories: fedora-cisco-openh264 fedora-modular updates-modular updates fedora google-chrome updates-archive
Updating metadata for 'updates-modular'... done
Updating metadata for 'updates'... done
Updating metadata for 'updates-archive'... done
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2023-03-14T10:56:46Z solvables: 4
rpm-md repo 'fedora-modular' (cached); generated: 2023-04-13T20:30:47Z solvables: 1082
rpm-md repo 'updates-modular'; generated: 2023-06-25T00:56:12Z solvables: 1077
rpm-md repo 'updates'; generated: 2023-06-26T00:33:31Z solvables: 17069
rpm-md repo 'fedora' (cached); generated: 2023-04-13T20:37:10Z solvables: 69222
rpm-md repo 'google-chrome' (cached); generated: 2023-06-23T18:51:52Z solvables: 3
rpm-md repo 'updates-archive'; generated: 2023-06-16T03:08:05Z solvables: 18277
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - package samba-2:4.18.3-3.fc38.x86_64 from updates requires samba-common = 2:4.18.3-3.fc38, but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libsamba-debug-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libreplace-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libgenrand-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libsamba-security-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libsamba3-util-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libsecrets3-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libcliauth-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libdcerpc-samba-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libsamba-sockets-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libdbwrap-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libmsrpc3-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libndr-samba-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libsamdb-common-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libcli-smb-common-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libgse-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires liblibsmb-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libndr-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libcommon-auth-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libsmbd-base-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libsocket-blocking-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libutil-tdb-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libevents-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libsys-rw-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libtime-basic-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libads-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libauth-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libsmbd-shim-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libutil-reg-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libCHARSET3-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libcli-cldap-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libcli-nbt-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libcli-spoolss-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libcmdline-contexts-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libmessages-dgm-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libprinting-migrate-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libmsghdr-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.1-0.fc38.x86_64 from fedora requires libsamba-cluster-support-samba4.so(SAMBA_4.18.1_SAMBA4)(64bit), but none of the providers can be installed
  - package samba-2:4.18.2-0.fc38.x86_64 from updates-archive requires libwbclient = 2:4.18.2-0.fc38, but none of the providers can be installed
  - package samba-2:4.18.3-0.fc38.x86_64 from updates-archive requires libwbclient = 2:4.18.3-0.fc38, but none of the providers can be installed
  - cannot install both samba-common-2:4.18.3-3.fc38.noarch from updates and samba-common-2:4.18.3-1.fc38.noarch from @System
  - cannot install both samba-client-libs-2:4.18.1-0.fc38.x86_64 from fedora and samba-client-libs-2:4.18.3-1.fc38.x86_64 from @System
  - cannot install both libwbclient-2:4.18.2-0.fc38.x86_64 from updates-archive and libwbclient-2:4.18.3-1.fc38.x86_64 from @System
  - cannot install both libwbclient-2:4.18.3-0.fc38.x86_64 from updates-archive and libwbclient-2:4.18.3-1.fc38.x86_64 from @System
```

I've tested installing it in a toolbox and it works fine (except some complaints from the post-script that are probably specific to toolbox) so I suspect this is a Silverblue-specific issue.

**Comment by travier** [comment] 2023-06-27 09:21
Looks like we have't had a successful build since 38.20230624.0 for Silverblue and Kinoite and somehow rpm-ostree can not resolve the dependencies here.

https://pagure.io/releng/failed-composes/issue/5120

**Comment by travier** [comment] 2023-06-27 09:25
I highly suspect that https://src.fedoraproject.org/rpms/samba/c/2d8a4bb6f8c2ca646f533cef47b4922e2c028863?branch=f38 is the culprit here and we can't do much but wait for a new compose.

**Comment by tpopela** [comment] 2023-06-27 09:28
@travier aren't we supposed to get an e-mail about failed composes after changes done in https://pagure.io/fedora-kickstarts/pull-request/961 ? I personally didn't receive any.

**Comment by travier** [comment] 2023-06-27 09:53
We should but apparently this does not work yet: https://pagure.io/releng/compose-tracker/pull-request/54

**Comment by sramkrishna** [comment] 2023-06-27 14:31
Thanks everyone for looking into this. Much appreciate your time and effort. 
I will say that I've had issues with samba updating for longer than the 24th - I feel not being able to update samba was there for awhile. In any case,

**Comment by travier** [comment] 2023-06-27 16:55
I can not reproduce the error from https://kojipkgs.fedoraproject.org//work/tasks/7799/102587799/runroot.log locally so I don't know where the issue is.

I've asked @AdamWill to test the unified core compose again so that we can try moving to it.

@sramkrishna How long has that been an issue? The suspected change that could break overlaying samba has been introduced with https://bodhi.fedoraproject.org/updates/FEDORA-2023-ef663b3ec4.

**Comment by travier** [comment] 2023-06-28 08:42
We have a new compose. Can you verify that you're able to install samba now?

**Comment by travier** [comment] 2023-06-28 09:00
This worked for me on the latest compose:

```
[silverblue@fedora ~]$ rpm-ostree status
State: idle
Deployments:
  fedora:fedora/38/x86_64/silverblue
                  Version: 38.20230628.0 (2023-06-28T00:42:50Z)
               BaseCommit: f3933b350390ee28c919dc4d5824682b8391a9e4deb56d767d02fcee18a3a9f9
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
                     Diff: 6 added
          LayeredPackages: samba

● fedora:fedora/38/x86_64/silverblue
                  Version: 38.20230628.0 (2023-06-28T00:42:50Z)
                   Commit: f3933b350390ee28c919dc4d5824682b8391a9e4deb56d767d02fcee18a3a9f9
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
```

**Closed by travier** 2023-06-28 09:00 UTC
Labels: bug, kinoite, f38

**Comment by sramkrishna** [comment] 2023-06-28 15:15
Thanks for addressing this so quickly. I'm not able to confirm it worked as I've moved to u-blue (I was seduced into trying it). Thanks so much for the time and effort and the fast response. Much obliged. There is a reason why silverblue is an amazing distro, thanks to people like you all. Cheers.
