### ISSUE TITLE
df throws warning/error

### ISSUE THREAD

**Issue by daniel-wtd** [fedora-silverblue/issue-tracker#104] opened 2020-11-17 11:46 UTC
Recently I discovered an issue with the `df` command:

```
# This works perfectly fine
root ~ $ df -h

# This does throw an error
dschier ~ $ df -h
df: /run/user/1000/doc: Operation not permitted
```

The directory is readable and the issue just occured recently. Any ideas whats happening here?

```
rpm-ostree status

State: idle
Deployments:
● ostree://fedora:fedora/33/x86_64/silverblue
                   Version: 33.20201117.0 (2020-11-17T00:48:12Z)
                BaseCommit: 7b002133773c2630d79d8838bb96e2d7090a80a4903ee5439bd5a62aed1efc07
              GPGSignature: Valid signature by 963A2BEB02009608FE67EA4249FD77499570FF31
           LayeredPackages: chromium chromium-libs-media-freeworld ffmpeg-libs micro solaar tmux virt-manager
             LocalPackages: rpmfusion-nonfree-release-33-1.noarch rpmfusion-free-release-33-1.noarch

  ostree://fedora:fedora/33/x86_64/silverblue
                   Version: 33.20201116.0 (2020-11-16T00:41:59Z)
                BaseCommit: 41c2e243f36ec6c34cb0e154c0bfbbf0a1ca95585718ab54ce27bb58844e1ed9
              GPGSignature: Valid signature by 963A2BEB02009608FE67EA4249FD77499570FF31
           LayeredPackages: chromium chromium-libs-media-freeworld ffmpeg-libs micro solaar tmux virt-manager
             LocalPackages: rpmfusion-nonfree-release-33-1.noarch rpmfusion-free-release-33-1.noarch
```

**Comment by tpopela** [comment] 2020-11-18 11:22
Duplicate of https://github.com/flatpak/xdg-desktop-portal/issues/512 (I will ask @matthiasclasen to reopen the issue)

**Closed by tpopela** 2020-11-18 11:22 UTC
