### ISSUE TITLE
Silverblue 33, problems with VM and SElinux

### ISSUE THREAD

**Issue by bnordgren** [fedora-silverblue/issue-tracker#94] opened 2020-11-03 22:06 UTC
Upgrading silverblue today, my VM setup failed. The problem is the same as: 

https://bugzilla.redhat.com/show_bug.cgi?id=1867308

My current install is: 

```
● ostree://fedora:fedora/33/x86_64/silverblue
                   Version: 33.20201103.0 (2020-11-03T00:40:42Z)
                BaseCommit: 89434c12f1f9ed475d84ae2e606efee843ad1b28ff20a19ac120ffed92051b75
              GPGSignature: Valid signature by 963A2BEB02009608FE67EA4249FD77499570FF31
           LayeredPackages: /usr/bin/virt-sysprep dkms filelight flash-plugin google-chrome-stable hugin libvirt qemu-kvm qtpass remmina
                            remmina-plugins-rdp singularity virt-manager
             LocalPackages: adobe-release-x86_64-1.0-1.noarch
```

The problem as noted in the bugzilla is  that systemd-machine fails to start due to an SElinux misconfiguration. My solution was to run `audit2allow` and add a new module.  The resulting *.te file is as follows: 

```
[root@brycelap ~]# cat systemd-machine.te

module systemd-machine 1.0;

require {
	type systemd_machined_t;
	type systemd_userdbd_runtime_t;
	class dir write;
}

#============= systemd_machined_t ==============
allow systemd_machined_t systemd_userdbd_runtime_t:dir write;
```

**Comment by tpopela** [comment] 2020-11-04 07:12
Hi @bnordgren ! Can you please reopen the usptream issue and state that the issue is not fixed?

**Comment by bnordgren** [comment] 2020-11-04 18:48
The short answer is no, I can't. However, I did reply to the person who closed it and asked them to re-open it.

**Comment by tpopela** [comment] 2020-11-05 06:21
I see, that you managed to comment there and I reopened the bug. Let me close this issue then.

**Closed by tpopela** 2020-11-05 06:21 UTC
