### ISSUE TITLE
[BUG] fedora silverblue grub configuration 

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#315] opened 2022-07-21 09:58 UTC
**Describe the bug**
installing fedora workstation next to fedora silverblue (dualboot) overrides grub configs rendering the first one installed unbootable

**To Reproduce**
1. have a silverblue install and a spare partition
2. install fedora workstation

**Expected behavior**
have 2 separate boot entries for the 2 operating systems 

**OS version:**
```
reproducible on all versions  
```
**an easy fix**
make it so that silverblue installs grub under /boot/efi/EFI/fedora silverblue/...  and workstation installs it under  /boot/efi/EFI/fedora workstation/...  instead of all editions installing to  /boot/efi/EFI/fedora/... so we can have multiple grub installs.

**Comment by travier** [comment] 2023-05-15 16:41
Closing as duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/284

**Closed by travier** 2023-05-15 16:41 UTC
Labels: enhancement
