### ISSUE TITLE
LUKS decrypt - always english keyboard

### ISSUE THREAD

**Issue by iatone93** [fedora-silverblue/issue-tracker#92] opened 2020-10-22 11:00 UTC
When i boot and need to decrypt the drive, the keyboard layout is always english, although i set it to be german. 

I noticed that the Fedora WS 33 doesnt have that bug anymore, but the Fedora SB 33 image does.

**Comment by tpopela** [comment] 2020-10-22 11:40
Duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/3

**Closed by tpopela** 2020-10-22 11:40 UTC
