### ISSUE TITLE
[BUG]  Rebase from silverblue 34 to 35 fails in GNOME Software

### ISSUE THREAD

**Issue by Zlopez** [fedora-silverblue/issue-tracker#221] opened 2021-11-02 14:51 UTC
**Describe the bug**
When trying to download F35 ostree image when updating through GNOME Software I'm getting error 
```
Unable to upgrade to Fedora Linux 35:
Invalid refspec ostree://fedora/35/x86_64/silverblue
```

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Open GNOME Software on F34 Silverblue
2. Go to Updates
3. Click Download

**Expected behavior**
F35 Silverblue gets downloaded

**Screenshots**
![Screenshot from 2021-11-02 15-47-27](https://user-images.githubusercontent.com/6943409/139870483-07dea8a8-ea9f-4bca-b413-8f0723d5a262.png)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/34/x86_64/silverblue
                   Version: 34.20211102.0 (2021-11-02T00:47:17Z)
                    Commit: 40ed9c75e49e61910323ee36238145522233ed81a1b98559d54ec131f62cd2f6
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
```

**Additional context**
This is what I found in the `journalctl -f`
```
Nov 02 15:44:25 fedora rpm-ostree[10332]: Locked sysroot
Nov 02 15:44:25 fedora rpm-ostree[10332]: Initiated txn Rebase for client(id:gnome-software dbus:1.111 unit:app-gnome-gnome\x2dsoftware\x2dservice-2226.scope uid:1000): /org/projectatomic/rpmostree1/fedora
Nov 02 15:44:25 fedora rpm-ostree[10332]: Process [pid: 2226 uid: 1000 unit: user@1000.service] connected to transaction progress
Nov 02 15:44:25 fedora rpm-ostree[10332]: Txn Rebase on /org/projectatomic/rpmostree1/fedora failed: Invalid refspec ostree://fedora/35/x86_64/silverblue
Nov 02 15:44:25 fedora rpm-ostree[10332]: Unlocked sysroot
```

My suspicion is the wrong ostree URL sent to GNOME Software.

When I did this through terminal, I did rebase like this `rpm-ostree rebase fedora:fedora/35/x86_64/silverblue`

**Comment by tpopela** [comment] 2021-11-02 15:30
This is a duplicate of issue 207

**Closed by tpopela** 2021-11-02 15:30 UTC
