### ISSUE TITLE
[BUG] GNOME Software: Operating System Updates Unavailable

### ISSUE THREAD

**Issue by delight-aug** [fedora-silverblue/issue-tracker#271] opened 2022-05-10 21:32 UTC
**Describe the bug**
GNOME Software stopped working. It can't load the Explore and Installed pages, and on the Updates page it says:
"Operating System Updates Unavailable
Your operating system is no longer supported. This means that it does not receive security updates. It is recommended that you upgrade to a more recent version."

**To Reproduce**
I've recently installed Fedora 35 and rebased onto `fedora:fedora/36/x86_64/silverblue`. At some point in time, close to Fedora 36 release, this has happened.

**Screenshots**

![image](https://user-images.githubusercontent.com/51861383/167724123-281f2798-4f82-4d65-986c-09ee2f344210.png)
![image](https://user-images.githubusercontent.com/51861383/167724191-21bb79ef-c859-4fea-9dee-50ad83e713bf.png)
![image](https://user-images.githubusercontent.com/51861383/167724138-d9bfcce6-1677-4116-b1c1-b2f3fd0509bd.png)

**OS version:**
```
State: busy
Transaction: refresh-md
  Initiator: client(id:gnome-software dbus:1.107 unit:app-gnome-org.gnome.Software-2082.scope uid:1000)
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220510.0 (2022-05-10T01:28:36Z)
                BaseCommit: 8e68c41bf30c73f76be8da7d1fd3be18d63ce33379ecf5c4267a5b42c20d9d74
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
       RemovedBasePackages: gnome-terminal-nautilus gnome-terminal 3.44.0-1.fc36
           LayeredPackages: akmod-nvidia cloudflare-warp ffmpeg gnome-console
                            gnome-console-nautilus gnome-text-editor gnome-tweaks syncthing
                            xorg-x11-drv-nvidia xorg-x11-drv-nvidia-cuda
                            xorg-x11-drv-nvidia-cuda-libs
             LocalPackages: cloudflare-release-3.0.0-el8.noarch
                            rpmfusion-free-release-36-1.noarch
                            rpmfusion-nonfree-release-36-1.noarch
```

**Additional context**
I've updated it manually, but it didn't help. Also tried running `rpm-ostree cleanup -bpm`, didn't help either.

**Comment by edfloreshz** [comment] 2022-05-10 22:09
I installed 36 beta yesterday and encountered the same issue, tried the same steps as @delight-aug but no results, I tried rebasing the stable version (35) and the issue went away but GNOME Software was still buggy.

**Comment by delight-aug** [comment] 2022-05-10 22:49
@edfloreshz, you mean GNOME Software became usable on 35? Have you tried rebasing back to 36 and see if it's usable?

**Comment by edfloreshz** [comment] 2022-05-10 22:52
The warning went away, still I couldn't add Flathub or download anything.

**Comment by tpopela** [comment] 2022-05-11 04:24
Duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/257

**Closed by tpopela** 2022-05-11 04:24 UTC

**Comment by edfloreshz** [comment] 2022-05-12 05:09
I ran `rpm-ostree rollback` and everything started working again.

**Comment by tpopela** [comment] 2022-05-12 06:20
Yes, that's expected, because you got into the deployment with older libsolv version that doesn't have the problems as the new one.
