### ISSUE TITLE
F33 'sudo: unable to mkdir /sudo: Operation not permitted'

### ISSUE THREAD

**Issue by cmurf** [fedora-silverblue/issue-tracker#73] opened 2020-07-31 23:45 UTC
Clean installed from Fedora-Silverblue-ostree-x86_64-Rawhide-20200731.n.0.iso (either auto partition btrfs or custom part lvm+ext4)

I get this error every time I use `sudo`

```
$ rpm-ostree status
State: idle
Deployments:
● ostree://fedora:fedora/rawhide/x86_64/silverblue
                   Version: Rawhide.20200731.n.0 (2020-07-31T06:46:18Z)
                BaseCommit: 41a8da28196f7e591051632a3a8a58cc0b12f977578059cd822be8795e753559
              GPGSignature: Valid signature by 963A2BEB02009608FE67EA4249FD77499570FF31
           LayeredPackages: strace

$ strace sudo ls -l
execve("/usr/bin/sudo", ["sudo", "ls", "-l"], 0x7ffc79946ef0 /* 45 vars */) = 0
access(0x7f4c0432d1c3, F_OK)            = -1 ENOENT (No such file or directory)
brk(NULL)                               = 0x559db7fd8000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffe55524a70) = -1 EINVAL (Invalid argument)
fcntl(0, F_GETFD)                       = 0
fcntl(1, F_GETFD)                       = 0
fcntl(2, F_GETFD)                       = 0
access(0x7f4c0432d1c3, F_OK)            = -1 ENOENT (No such file or directory)
access(0x7f4c04330b30, R_OK)            = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x7ffe55523b70, O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat(0x7ffe55523b70, 0x7ffe55523c20)    = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x7ffe55523b70, O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat(0x7ffe55523b70, 0x7ffe55523c20)    = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x7ffe55523b70, O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat(0x7ffe55523b70, 0x7ffe55523c20)    = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x7ffe55523b70, O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat(0x7ffe55523b70, 0x7ffe55523c20)    = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x7ffe55523b70, O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat(0x7ffe55523b70, 0x7ffe55523c20)    = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x7ffe55523b70, O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat(0x7ffe55523b70, 0x7ffe55523c20)    = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x7ffe55523b70, O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat(0x7ffe55523b70, 0x7ffe55523c20)    = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x7ffe55523b70, O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat(0x7ffe55523b70, 0x7ffe55523c20)    = 0
openat(AT_FDCWD, 0x7f4c0432dc24, O_RDONLY|O_CLOEXEC) = 3
fstat(3, 0x7ffe55523bd0)                = 0
mmap(NULL, 61331, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f4c042fb000
close(3)                                = 0
openat(AT_FDCWD, 0x7f4c04337e20, O_RDONLY|O_CLOEXEC) = 3
read(3, 0x7ffe55523d78, 832)            = 832
fstat(3, 0x7ffe55523c20)                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4c042f9000
mmap(NULL, 176296, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f4c042cd000
mprotect(0x7f4c042d0000, 110592, PROT_NONE) = 0
mmap(0x7f4c042d0000, 32768, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7f4c042d0000
mmap(0x7f4c042d8000, 73728, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xb000) = 0x7f4c042d8000
mmap(0x7f4c042eb000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1d000) = 0x7f4c042eb000
mmap(0x7f4c042ed000, 45224, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f4c042ed000
close(3)                                = 0
openat(AT_FDCWD, 0x7ffe55523b50, O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x7f4c042f94d0, O_RDONLY|O_CLOEXEC) = 3
read(3, 0x7ffe55523d58, 832)            = 832
fstat(3, 0x7ffe55523c00)                = 0
mmap(NULL, 181736, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f4c042a0000
mmap(0x7f4c042a7000, 106496, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x7000) = 0x7f4c042a7000
mmap(0x7f4c042c1000, 32768, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x21000) = 0x7f4c042c1000
mmap(0x7f4c042c9000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x28000) = 0x7f4c042c9000
mmap(0x7f4c042cb000, 5608, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f4c042cb000
close(3)                                = 0
openat(AT_FDCWD, 0x7ffe55523b30, O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x7f4c042f99c0, O_RDONLY|O_CLOEXEC) = 3
read(3, 0x7ffe55523d38, 832)            = 832
fstat(3, 0x7ffe55523be0)                = 0
mmap(NULL, 16392, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f4c0429b000
mmap(0x7f4c0429c000, 4096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7f4c0429c000
mmap(0x7f4c0429d000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f4c0429d000
mmap(0x7f4c0429e000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f4c0429e000
mmap(0x7f4c0429f000, 8, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f4c0429f000
close(3)                                = 0
openat(AT_FDCWD, 0x7ffe55523b10, O_RDONLY|O_CLOEXEC) = 3
read(3, 0x7ffe55523d18, 832)            = 832
fstat(3, 0x7ffe55523bc0)                = 0
mmap(NULL, 125192, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f4c0427c000
mmap(0x7f4c04282000, 69632, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6000) = 0x7f4c04282000
mmap(0x7f4c04293000, 24576, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7f4c04293000
mmap(0x7f4c04299000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c000) = 0x7f4c04299000
close(3)                                = 0
openat(AT_FDCWD, 0x7ffe55523af0, O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x7f4c042fa3d0, O_RDONLY|O_CLOEXEC) = 3
read(3, 0x7ffe55523cf8, 832)            = 832
pread64(3, 0x7ffe55523be0, 48, 792)     = 48
pread64(3, 0x7ffe55523b90, 68, 840)     = 68
fstat(3, 0x7ffe55523ba0)                = 0
mmap(NULL, 135600, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f4c0425a000
mmap(0x7f4c04261000, 65536, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x7000) = 0x7f4c04261000
mmap(0x7f4c04271000, 20480, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7f4c04271000
mmap(0x7f4c04276000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1b000) = 0x7f4c04276000
mmap(0x7f4c04278000, 12720, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f4c04278000
close(3)                                = 0
openat(AT_FDCWD, 0x7ffe55523ad0, O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x7f4c042fa8c0, O_RDONLY|O_CLOEXEC) = 3
read(3, 0x7ffe55523cd8, 832)            = 832
fstat(3, 0x7ffe55523b80)                = 0
mmap(NULL, 24688, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f4c04253000
mmap(0x7f4c04255000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f4c04255000
mmap(0x7f4c04257000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7f4c04257000
mmap(0x7f4c04258000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7f4c04258000
mmap(0x7f4c04259000, 112, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f4c04259000
close(3)                                = 0
openat(AT_FDCWD, 0x7ffe55523ab0, O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x7f4c042fadb0, O_RDONLY|O_CLOEXEC) = 3
read(3, 0x7ffe55523cb8, 832)            = 832
pread64(3, 0x7ffe555238c0, 784, 64)     = 784
pread64(3, 0x7ffe55523880, 48, 848)     = 48
pread64(3, 0x7ffe55523830, 68, 896)     = 68
fstat(3, 0x7ffe55523b60)                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4c04251000
pread64(3, 0x7ffe555237a0, 784, 64)     = 784
mmap(NULL, 1880736, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f4c04085000
mprotect(0x7f4c040ab000, 1687552, PROT_NONE) = 0
mmap(0x7f4c040ab000, 1372160, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7f4c040ab000
mmap(0x7f4c041fa000, 311296, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x175000) = 0x7f4c041fa000
mmap(0x7f4c04247000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c1000) = 0x7f4c04247000
mmap(0x7f4c0424d000, 12960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f4c0424d000
close(3)                                = 0
openat(AT_FDCWD, 0x7f4c042514d0, O_RDONLY|O_CLOEXEC) = 3
read(3, 0x7ffe55523c98, 832)            = 832
fstat(3, 0x7ffe55523b40)                = 0
mmap(NULL, 28696, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f4c0407d000
mmap(0x7f4c0407f000, 12288, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f4c0407f000
mmap(0x7f4c04082000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5000) = 0x7f4c04082000
mmap(0x7f4c04083000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5000) = 0x7f4c04083000
close(3)                                = 0
openat(AT_FDCWD, 0x7f4c04251a10, O_RDONLY|O_CLOEXEC) = 3
read(3, 0x7ffe55523c78, 832)            = 832
fstat(3, 0x7ffe55523b20)                = 0
mmap(NULL, 623176, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f4c03fe4000
mmap(0x7f4c03fe7000, 438272, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7f4c03fe7000
mmap(0x7f4c04052000, 167936, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6e000) = 0x7f4c04052000
mmap(0x7f4c0407b000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x96000) = 0x7f4c0407b000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4c03fe2000
arch_prctl(ARCH_SET_FS, 0x7f4c03fe2d00) = 0
mprotect(0x7f4c04247000, 12288, PROT_READ) = 0
mprotect(0x7f4c04276000, 4096, PROT_READ) = 0
mprotect(0x7f4c0407b000, 4096, PROT_READ) = 0
mprotect(0x7f4c04083000, 4096, PROT_READ) = 0
mprotect(0x7f4c04258000, 4096, PROT_READ) = 0
mprotect(0x7f4c04299000, 4096, PROT_READ) = 0
mprotect(0x7f4c0429e000, 4096, PROT_READ) = 0
mprotect(0x7f4c042c9000, 4096, PROT_READ) = 0
mprotect(0x7f4c042eb000, 4096, PROT_READ) = 0
mprotect(0x559db69d3000, 4096, PROT_READ) = 0
mprotect(0x7f4c04335000, 4096, PROT_READ) = 0
munmap(0x7f4c042fb000, 61331)           = 0
set_tid_address(0x7f4c03fe2fd0)         = 2968
set_robust_list(0x7f4c03fe2fe0, 24)     = 0
rt_sigaction(SIGRTMIN, 0x7ffe55524890, NULL, 8) = 0
rt_sigaction(SIGRT_1, 0x7ffe55524890, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, 0x7ffe55524a08, NULL, 8) = 0
prlimit64(0, RLIMIT_STACK, NULL, 0x7ffe555249f0) = 0
statfs(0x7f4c042c1843, 0x7ffe555249c0)  = 0
statfs(0x7f4c042c1843, 0x7ffe555248b0)  = 0
brk(NULL)                               = 0x559db7fd8000
brk(0x559db7ff9000)                     = 0x559db7ff9000
access(0x7f4c042c186b, F_OK)            = 0
prlimit64(0, RLIMIT_AS, NULL, 0x559db69d4088) = 0
prlimit64(0, RLIMIT_AS, 0x559db69d4078, NULL) = 0
prlimit64(0, RLIMIT_CPU, NULL, 0x559db69d40c0) = 0
prlimit64(0, RLIMIT_CPU, 0x559db69d40b0, NULL) = 0
prlimit64(0, RLIMIT_DATA, NULL, 0x559db69d40f8) = 0
prlimit64(0, RLIMIT_DATA, 0x559db69d40e8, NULL) = 0
prlimit64(0, RLIMIT_FSIZE, NULL, 0x559db69d4130) = 0
prlimit64(0, RLIMIT_FSIZE, 0x559db69d4120, NULL) = 0
prlimit64(0, RLIMIT_NOFILE, NULL, 0x559db69d4168) = 0
prlimit64(0, RLIMIT_NOFILE, 0x559db69d4158, NULL) = -1 EPERM (Operation not permitted)
prlimit64(0, RLIMIT_NOFILE, 0x559db69d4040, NULL) = -1 EPERM (Operation not permitted)
prlimit64(0, RLIMIT_NOFILE, 0x559db69d4158, NULL) = 0
prlimit64(0, RLIMIT_NPROC, NULL, 0x559db69d41a0) = 0
prlimit64(0, RLIMIT_NPROC, 0x559db69d4190, NULL) = -1 EPERM (Operation not permitted)
prlimit64(0, RLIMIT_NPROC, 0x559db69d4190, NULL) = 0
prlimit64(0, RLIMIT_RSS, NULL, 0x559db69d41d8) = 0
prlimit64(0, RLIMIT_RSS, 0x559db69d41c8, NULL) = 0
prlimit64(0, RLIMIT_STACK, NULL, 0x559db69d4210) = 0
prlimit64(0, RLIMIT_STACK, 0x559db69d4200, NULL) = 0
fcntl(0, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(1, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(2, F_GETFL)                       = 0x2 (flags O_RDWR)
openat(AT_FDCWD, 0x7f4c0421caa0, O_RDONLY|O_CLOEXEC) = 3
fstat(3, 0x7f4c0424c600)                = 0
mmap(NULL, 223542144, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f4bf6ab2000
close(3)                                = 0
openat(AT_FDCWD, 0x7f4c042161b3, O_RDONLY|O_CLOEXEC) = 3
fstat(3, 0x7ffe55524760)                = 0
fstat(3, 0x7ffe55524590)                = 0
read(3, 0x559db7fd9660, 4096)           = 2444
lseek(3, -1550, SEEK_CUR)               = 894
read(3, 0x559db7fd9660, 4096)           = 1550
close(3)                                = 0
stat(0x7f4c042940fc, 0x7ffe55524670)    = 0
openat(AT_FDCWD, 0x7f4c042940fc, O_RDONLY) = -1 EACCES (Permission denied)
geteuid()                               = 1000
geteuid()                               = 1000
access(0x7ffe55523830, X_OK)            = -1 ENOENT (No such file or directory)
access(0x7ffe55523830, X_OK)            = -1 ENOENT (No such file or directory)
access(0x7ffe55523830, X_OK)            = -1 ENOENT (No such file or directory)
access(0x7ffe55523830, X_OK)            = -1 ENOENT (No such file or directory)
access(0x7ffe55523830, X_OK)            = 0
stat(0x7ffe55523830, 0x7ffe555237a0)    = 0
openat(AT_FDCWD, 0x7ffe55523310, O_RDONLY|O_CLOEXEC) = 3
fstat(3, 0x7ffe55523140)                = 0
read(3, 0x559db7fdac60, 4096)           = 2998
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, 0x559db7fdacd0, O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x559db7fdaee0, O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x559db7fdad60, O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x559db7fdae60, O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x559db7fdaf70, O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, 0x559db7fdade0, O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, 0x7ffe555263bd, 4sudo)             = 4
write(2, 0x7f4c042936b6, 2: )             = 2
write(2, 0x7ffe555211a0, 133effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?)           = 133
ioctl(2, TCGETS, 0x7ffe55523140)        = 0
)             = 124b4c3, 1
write(2, 0x7f4c0424b4c3, 1
)             = 1
exit_group(1)                           = ?
+++ exited with 1 +++
$ 
```

**Comment by tpopela** [comment] 2020-08-03 04:35
@cgwalters @dustymabe any idea?

**Comment by cgwalters** [comment] 2020-08-03 13:09
Unfortunately `strace` changes the behavior of suid apps so we're not seeing the real error here.  Does it reproduce if you run `sudo` when you're already root? 

Do you have any non-default PAM configuration?

**Comment by cmurf** [comment] 2020-08-03 17:03
>Does it reproduce if you run sudo when you're already root?

No.

>Do you have any non-default PAM configuration?

No. It's a clean install->g-i-s->go directly to Terminal to `sudo ls -l` and get this error.

**Comment by TheOneandOnlyJakfrost** [comment] 2020-08-03 20:39
I get the message 

> sudo: unable to mkdir /sudo: Operation not permitted

In a terminal when I enter `sudo ls -l` but the output of the command is correct. I have seen this on another system with F33 Silverblue rawhide, the command used then was `sudo flatpak repair`. It doesn't seem to affect the command from working, just an annoying message for me right now. Both systems are a clean rawhide install.

**Comment by cmurf** [comment] 2020-08-03 21:49
Yes, the command does succeed despite the error. There are two unexpected consequences: (a) the reported error (b) the authentication timeout is immediate, i.e. immediately using sudo again, I'm also required to authenticate again.

**Comment by tijolao** [comment] 2020-08-23 20:12
I'm having this problem too with Silverblue 33.

**Comment by dustymabe** [comment] 2020-09-14 22:09
In OSTree based systems the root `/` directory is immutable. Which means things like `mkdir /sudo` won't work. I'd be interested to know why something is trying to create that directory.

**Comment by TheOneandOnlyJakfrost** [comment] 2020-09-15 12:33
Could it have something to do with sudo itself? Maybe it has changed recently. I have version 1.9.1 which has [this change](https://www.sudo.ws/repos/sudo/rev/839a9a9c0cc3), that seems to indicate writing info automatically into sudo.conf

**Comment by dustymabe** [comment] 2020-09-15 14:07
Right, my guess is that it is probably a change in `sudo` in f33.

**Comment by dustymabe** [comment] 2020-09-16 17:17
on my non Silverblue system `/sudo/ts/dustymabe/` exists and is binary data:

```
$ sudo file /sudo/ts/dustymabe
/sudo/ts/dustymabe: data
```

**Comment by mscherer** [comment] 2020-09-16 17:27
ts is for timestamp. It should go to _PATH_SUDO_TIMEDIR, which is defined as "$rundir/ts" in ./m4/sudo.m4, e.g /var/run/sudo.

Maybe this directory is not present and sudo fallback to / ? I tested in a container and it created /sudo, and there is no /var/run/sudo on the fs

**Comment by dustymabe** [comment] 2020-09-16 18:08
looks like this is fixed in a future update (not yet in updates-testing) https://bugzilla.redhat.com/show_bug.cgi?id=1868215

**Comment by tpopela** [comment] 2020-10-08 09:35
I can't reproduce it on current Silverblue 33 that contains the builds mentioned in bug linked by Dusty.

$ rpm -qa | grep sudo
sudo-1.9.2-1.fc33.x86_64

**Closed by tpopela** 2020-10-08 09:35 UTC
