### ISSUE TITLE
Firmware update for UEFI (fwupd) cannot be applied

### ISSUE THREAD

**Issue by rugk** [fedora-silverblue/issue-tracker#381] opened 2022-11-13 18:33 UTC
**Describe the bug**
I cannot update UEFI firmware via fwupd.

GNOME Software shows me this update:
![grafik](https://user-images.githubusercontent.com/11966684/201537806-3bb01be9-1751-4ac0-90b5-299ffa9f130e.png)

**To Reproduce**
1. I click on GNOME Software on that button.
-> Nothing happened,  no error shown or so.

So I switched to the CLI and the error persists.

**Expected behavior**
Update should be applied.

**Log**
```
$ sudo fwupdtool update                
Laden …                  [-                                      ]
Geräte mit keinen verfügbaren Firmware-Aktualisierungen: 
 • ELAN0001:00 04F3:3140
╔══════════════════════════════════════════════════════════════════════════════╗
║ UEFI dbx von 83 auf 217 aktualisieren?                                       ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ This updates the dbx to the latest release from Microsoft which adds         ║
║ insecure versions of grub and shim to the list of forbidden signatures due   ║
║ to multiple discovered security updates.                                     ║
║                                                                              ║
║ Before installing the update, fwupd will check for any affected executables  ║
║ in the ESP and will refuse to update if it finds any boot binaries signed    ║
║ with any of the forbidden signatures.If the installation fails, you will     ║
║ need to update shim and grub packages before the update can be deployed.     ║
║                                                                              ║
║ Once you have installed this dbx update, any DVD or USB installer images     ║
║ signed with the old signatures may not work correctly.You may have to        ║
║ temporarily turn off secure boot when using recovery or installation media,  ║
║ if new images have not been made available by your distribution.             ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝

Operation durchführen? [Y|n]: Y
Schreiben …              [***************************************]
Herunterladen …          [***************************************]
Warten …                 [***************************************]
Schreiben …              [***************************************]
Gerät wird neu gestartet …[***************************************]
Schreiben …              [***************************************]
Entpacken …              [***************************************]
Blocked executable in the ESP, ensure grub and shim are up to date: /boot/efi/EFI/BOOT/BOOTX64.EFI Authenticode checksum [0ce02100f67c7ef85f4eed368f02bf7092380a3c23ca91fd7f19430d94b00c19] is present in dbx

Ein Neustart ist erforderlich, um eine Aktualisierung abzuschließen. Jetzt neu starten? [y|N]:
```

(Even if I choose to reboot after the last message, the update is not applied.)

Interesting:
```
$ sudo fwupdtool watch                 
Laden …                  [****                                   ]18:29:24:0982 FuPluginUefiCapsule  SMBIOS BIOS Characteristics Extension Byte 2 is invalid -- UEFI Specification is unsupported, but /sys/firmware/efi exists: SMBIOS not supported
Laden …                  [-                                      ]
sudo fwupdate -L       
failed: Error opening file /sys/firmware/efi/efivars/FWUPDATE_DEBUG_LOG-0abba7dc-e516-4167-bbf5-4d9d1c739416: No such file or directory
$ sudo ls -la /sys/firmware/efi/efivars/                                                   
total 0
drwxr-xr-x. 2 root root    0 Nov 13 19:23 .
drwxr-xr-x. 5 root root    0 Nov 13 19:23 ..
-rw-r--r--. 1 root root  132 Nov 13 19:23 AMD_PBS_SETUP-a339d746-f678-49b3-9fc7-54ce0f9df226
-rw-r--r--. 1 root root   14 Nov 13 19:23 AmdAcpiVar-79941ecd-ed36-49d0-8124-e4c31ac75cd4
-rw-r--r--. 1 root root   38 Nov 13 19:23 AmdPlatformSetup-95fdeb3e-b1c9-4eb7-a936-86154a5fa760
-rw-r--r--. 1 root root 1375 Nov 13 19:23 AmdSetup-3a997502-647a-4c82-998e-52ef9486a247
-rw-r--r--. 1 root root    8 Nov 13 19:23 ApSyncFlagNv-ad3f6761-f0a3-46c8-a4cb-19b70ffdb305
-rw-r--r--. 1 root root   26 Nov 13 19:23 AppName-1fd8b79f-0be2-4d57-b241-81c5e24e01a1
-rw-r--r--. 1 root root   36 Nov 13 19:23 AppPlatform-1fd8b79f-0be2-4d57-b241-81c5e24e01a1
-rw-r--r--. 1 root root  122 Nov 13 19:23 Boot0000-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root  304 Nov 13 19:23 Boot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   46 Nov 13 19:23 Boot0010-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   54 Nov 13 19:23 Boot0011-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   70 Nov 13 19:23 Boot0012-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   68 Nov 13 19:23 Boot0013-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root  162 Nov 13 19:23 Boot0014-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   69 Nov 13 19:23 Boot0015-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   71 Nov 13 19:23 Boot0016-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   70 Nov 13 19:23 Boot0017-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   68 Nov 13 19:23 Boot0018-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   68 Nov 13 19:23 Boot0019-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   66 Nov 13 19:23 Boot001A-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root    6 Nov 13 19:23 BootCurrent-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root    8 Nov 13 19:23 BootOptionSupport-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   22 Nov 13 19:23 BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   18 Nov 13 19:23 BootOrderDefault-0b7646a4-6b44-4332-8588-c8998117f2ef
-rw-r--r--. 1 root root    5 Nov 13 19:23 CheckFirstBoot-59d1c24f-50f1-401a-b101-f33e0daed443
-rw-r--r--. 1 root root   78 Nov 13 19:23 ConIn-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   38 Nov 13 19:23 ConInDev-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   40 Nov 13 19:23 ConOut-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   40 Nov 13 19:23 ConOutDev-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root    5 Nov 13 19:23 ConfigurationPagePrivate-a55897c4-12ff-409f-920b-bd77cc40c396
-rw-r--r--. 1 root root    5 Nov 13 19:23 CurrentPolicy-77fa9abd-0359-4d32-bd60-28f4e78f784b
-rw-r--r--. 1 root root    6 Nov 13 19:23 DIAGSPLSHSCRN-a7d8d9a6-6ab0-4aeb-ad9d-163e59a7a380
-rw-r--r--. 1 root root    5 Nov 13 19:23 DownCoreStatus-29749bad-401b-4f6d-b124-cece8c590c48
-rw-r--r--. 1 root root   44 Nov 13 19:23 ESRTPLATFORMENTRY-3771d7f2-ff2e-4963-87b1-862d93a037da
-rw-r--r--. 1 root root   44 Nov 13 19:23 ESRTPLATFORMENTRY-b0a396ce-5357-494d-b243-9264c227ead0
-rw-r--r--. 1 root root   40 Nov 13 19:23 ErrOutDev-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   68 Nov 13 19:23 EventLog-57a34c69-4d62-0b7e-86e4-939c5c9b7c93
-rw-r--r--. 1 root root    8 Nov 13 19:23 FBSWIF-d743491e-f484-4952-a87d-8d5dd189b70c
-rw-r--r--. 1 root root   12 Nov 13 19:23 HDDPWD-c7e07e07-fd36-4da6-8ec0-8954521f04db
-rw-r--r--. 1 root root   18 Nov 13 19:23 HDD_Password_Status-0dffc7df-49b6-4562-b9bf-e51c2b6e1b1c
-rw-r--r--. 1 root root    8 Nov 13 19:23 Intel-pwrovr-74b00bd9-805a-4d61-b51f-43268123d113
-rw-r--r--. 1 root root 1564 Nov 13 19:23 KEK-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root  318 Nov 13 19:23 Key0000-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root  206 Nov 13 19:23 Key0001-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   94 Nov 13 19:23 Key0002-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   94 Nov 13 19:23 Key0003-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   11 Nov 13 19:23 L05OkrData-9669e125-fedf-43f7-891a-5af85efcdefc
-rw-r--r--. 1 root root   13 Nov 13 19:23 LBATINFO-01c9c8d4-743d-4fc5-bc12-e0398a45d540
-rw-r--r--. 1 root root   14 Nov 13 19:23 LBLDESP-871455d0-5576-4fb8-9865-af0824463b9e
-rw-r--r--. 1 root root   44 Nov 13 19:23 LBLDVC-871455d1-5576-4fb8-9865-af0824463c9f
-rw-r--r--. 1 root root    6 Nov 13 19:23 LastBootCurrent-0b7646a4-6b44-4332-8588-c8998117f2ef
-rw-r--r--. 1 root root   22 Nov 13 19:23 LastBootOrder-0b7646a4-6b44-4332-8588-c8998117f2ef
-rw-r--r--. 1 root root   32 Nov 13 19:23 LoadOptionCrcTable-0b7646a4-6b44-4332-8588-c8998117f2ef
-rw-r--r--. 1 root root    5 Nov 13 19:23 LvarSmiReadyFlag-6acce65d-da35-4b39-b64b-5ed927a7dc7e
-rw-r--r--. 1 root root    8 Nov 13 19:23 MTC-eb704011-1402-11d3-8e77-00a0c969723b
-rw-r--r--. 1 root root    5 Nov 13 19:23 MemoryOverwriteRequestControl-e20939be-32d4-41be-a150-897f85d49829
-rw-r--r--. 1 root root    5 Nov 13 19:23 MemoryOverwriteRequestControlLock-bb983ccf-151d-40e1-a07b-4a17be168292
-rw-r--r--. 1 root root  260 Nov 13 19:23 OfflineUniqueIDEKPub-eaec226f-c9a3-477a-a826-ddc716cdc0e3
-rw-r--r--. 1 root root    8 Nov 13 19:23 OfflineUniqueIDEKPubCRC-eaec226f-c9a3-477a-a826-ddc716cdc0e3
-rw-r--r--. 1 root root   36 Nov 13 19:23 OilRetentionVariable-77060029-8f21-442a-b692-8d29c8af5826
-rw-r--r--. 1 root root   69 Nov 13 19:23 OilSetup-88d1911c-ab4a-4335-9e9a-26be9081acc3
-rw-r--r--. 1 root root   13 Nov 13 19:23 OilSetupPreLoadLangage-074e3792-c22e-11e9-9cb5-2a2ae2dbcce4
-rw-r--r--. 1 root root    5 Nov 13 19:23 OilSetupVarInited-047b3447-d95b-48ee-9aae-b88cc263ec63
-rw-r--r--. 1 root root   32 Nov 13 19:23 OrgLoadOptionCrcTable-0b7646a4-6b44-4332-8588-c8998117f2ef
-rw-r--r--. 1 root root   12 Nov 13 19:23 OsIndications-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   12 Nov 13 19:23 OsIndicationsSupported-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root  856 Nov 13 19:23 PK-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   16 Nov 13 19:23 PbaStatusVar-0ec1a7f5-4904-40a0-8eab-4bcc4666da45
-rw-r--r--. 1 root root   10 Nov 13 19:23 PlatformLang-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   28 Nov 13 19:23 PlatformLangCodes-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   18 Nov 13 19:23 PreDefinedBootOptions-0b7646a4-6b44-4332-8588-c8998117f2ef
-rw-r--r--. 1 root root   18 Nov 13 19:23 ProtectedBootOptions-0b7646a4-6b44-4332-8588-c8998117f2ef
-rw-r--r--. 1 root root   20 Nov 13 19:23 RTCALARM-378d7b65-8da9-4773-b6e4-a47826a833e1
-rw-r--r--. 1 root root   12 Nov 13 19:23 ReservedConfiguration-74d69abb-57c3-4d7f-bfb4-26a2549610f1
-rw-r--r--. 1 root root   36 Nov 13 19:23 SFRM_NVRAM-c2873663-b2cb-4f7a-8548-a60411f5ec86
-rw-r--r--. 1 root root 3062 Nov 13 19:23 SMBIOSELOG000-c3eeae98-23bf-412b-ab60-efcbb48e1534
-rw-r--r--. 1 root root    5 Nov 13 19:23 SMBIOSELOGNUMBER-c3eeae98-23bf-412b-ab60-efcbb48e1534
-rw-r--r--. 1 root root   12 Nov 13 19:23 SMBIOSMEMSIZE-c3eeae98-23bf-412b-ab60-efcbb48e1534
-rw-r--r--. 1 root root    5 Nov 13 19:23 SecureBoot-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   45 Nov 13 19:23 Setup-4dfbbaab-1392-4fde-abb8-c41cc5ad7d5d
-rw-r--r--. 1 root root    5 Nov 13 19:23 SetupMode-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   68 Nov 13 19:23 SignatureSupport-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root    5 Nov 13 19:23 Size17or1514-5e3f081a-f9fb-4d7d-b7ef-2c4d0064da82
-rw-r--r--. 1 root root   67 Nov 13 19:23 System-e947fcf9-dd01-4965-b808-32a7b6815657
-rw-r--r--. 1 root root   20 Nov 13 19:23 Tcg2PhysicalPresence-aeb9c5c1-94f1-4d02-bfd9-4602db2d3c54
-rw-r--r--. 1 root root    8 Nov 13 19:23 Tcg2PhysicalPresenceFlags-aeb9c5c1-94f1-4d02-bfd9-4602db2d3c54
-rw-r--r--. 1 root root    6 Nov 13 19:23 Timeout-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   36 Nov 13 19:23 UnlockIDCopy-eaec226f-c9a3-477a-a826-ddc716cdc0e3
-rw-r--r--. 1 root root   89 Nov 13 19:23 UserManagerVar-1ef17197-2cce-49d6-a6ce-4012f338a76e
-rw-r--r--. 1 root root    5 Nov 13 19:23 VarErrorFlag-04b37fe8-f6ae-480b-bdd5-37d98c5e89aa
-rw-r--r--. 1 root root    5 Nov 13 19:23 VendorKeys-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r--. 1 root root   94 Nov 13 19:23 certdb-d9bee56e-75dc-49d9-b4d7-b534210f637a
-rw-r--r--. 1 root root    8 Nov 13 19:23 certdbv-d9bee56e-75dc-49d9-b4d7-b534210f637a
-rw-r--r--. 1 root root 4694 Nov 13 19:23 db-d719b2cb-3d3a-4596-a3bc-dad00e67656f
-rw-r--r--. 1 root root 4044 Nov 13 19:23 dbx-d719b2cb-3d3a-4596-a3bc-dad00e67656f
-rw-r--r--. 1 root root  122 Nov 13 19:23 lBoot0000-146b234d-4052-4e07-b326-11220f8e1fe8
-rw-r--r--. 1 root root  168 Nov 13 19:23 lBoot0001-146b234d-4052-4e07-b326-11220f8e1fe8
-rw-r--r--. 1 root root   46 Nov 13 19:23 lBoot0010-146b234d-4052-4e07-b326-11220f8e1fe8
-rw-r--r--. 1 root root   54 Nov 13 19:23 lBoot0011-146b234d-4052-4e07-b326-11220f8e1fe8
-rw-r--r--. 1 root root   70 Nov 13 19:23 lBoot0012-146b234d-4052-4e07-b326-11220f8e1fe8
-rw-r--r--. 1 root root   68 Nov 13 19:23 lBoot0013-146b234d-4052-4e07-b326-11220f8e1fe8
-rw-r--r--. 1 root root  146 Nov 13 19:23 lBoot0014-146b234d-4052-4e07-b326-11220f8e1fe8
-rw-r--r--. 1 root root   75 Nov 13 19:23 lBoot0015-146b234d-4052-4e07-b326-11220f8e1fe8
-rw-r--r--. 1 root root   71 Nov 13 19:23 lBoot0016-146b234d-4052-4e07-b326-11220f8e1fe8
-rw-r--r--. 1 root root   77 Nov 13 19:23 lBoot0017-146b234d-4052-4e07-b326-11220f8e1fe8
-rw-r--r--. 1 root root  109 Nov 13 19:23 lBoot0018-146b234d-4052-4e07-b326-11220f8e1fe8
-rw-r--r--. 1 root root  109 Nov 13 19:23 lBoot0019-146b234d-4052-4e07-b326-11220f8e1fe8
-rw-r--r--. 1 root root  107 Nov 13 19:23 lBoot001A-146b234d-4052-4e07-b326-11220f8e1fe8
$ sudo fwupdate -L                      
failed: Error opening file /sys/firmware/efi/efivars/FWUPDATE_DEBUG_LOG-0abba7dc-e516-4167-bbf5-4d9d1c739416: No such file or directory
```

**OS version:**
```
rpm-ostree status -b
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
BootedDeployment:
* fedora:fedora/36/x86_64/silverblue
                  Version: 36.20221113.0 (2022-11-13T00:46:40Z)
               BaseCommit: 657961377488fd96a2266c766392e30e54c11bae144ad38293d50fad2a2dc524
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
          LayeredPackages: *****
```

**Additional context**
N/A

**Comment by tpopela** [comment] 2022-11-14 06:18
Duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/120

**Closed by tpopela** 2022-11-14 06:18 UTC
Labels: bug
