### ISSUE TITLE
34.20210424: gnome-shell freaks out inside a Virtualbox

### ISSUE THREAD

**Issue by arteeh** [fedora-silverblue/issue-tracker#153] opened 2021-04-25 11:14 UTC
When running Fedora Silverblue 34 inside a virtual machine in Virtualbox (host computer is Windows 10), some actions cause the shell to freak out and become unusable. This started happening after an upgrade from `34.20210420` to `34.20210424`. I've checked and the VM does not run out of memory or storage. I have the Virtualbox Extension Pack installed.

How to reproduce:

- Install and start Silverblue inside Virtualbox
- Upgrade to 34 with `rpm-ostree rebase fedora:fedora/34/x86_64/silverblue`
- Upgrade to version `34.20210424` (or later) in this branch
- Open Settings and go to Background
- Switch from a normal background to GNOME's dynamic background

This should then cause the shell to go black and freak out. A logout or restart undoes it. Switching backgrounds isn't the only thing causing this: sometimes when I switch tabs in Epiphany (Flatpak) the same problem occurs. I think moving and resizing windows can also be a trigger.

rpm-ostree status when running the broken version:

```
State:idle
Deployments:
● ostree://fedora:fedora/34/x86_64/silverblue
		Version:34.20210424.n.0(2021-04-24T08:00:52Z)
		Commit:2894808483974dfb1f30ad6dd537e83e93831ce1d5aa5d6740ce6a58f0fc35b0
		GPGSignature:Validsignatureby8C5BA6990BDB26E19F2A1A801161AE6945719A39

	ostree://fedora:fedora/34/x86_64/silverblue
		Version:34.20210420.n.0(2021-04-20T08:16:16Z)
		Commit:ae0390928fa9b2fcb61be3b41620d2ebaeb3423aa62d646335fcd553c5c01cde
		GPGSignature:Validsignatureby8C5BA6990BDB26E19F2A1A801161AE6945719A39
```

Package changes when rolling back to the previous version:

```
Upgraded:
	shim-x64 15.4-4 -> 15-8
Downgraded:
	at-spi2-core 2.40.0-2.fc34 -> 2.40.0-1.fc34
	dracut 053-4.fc34 -> 053-2.fc34
	efi-filesystem 5-2.fc34 -> 4-6.fc34
	firefox 87.0-12.fc34 -> 87.0-7.fc34
	gnome-shell 40.0-3.fc34 -> 40.0-1.fc34
	ibus-anthy 1.5.12-6.fc34 -> 1.5.12-4.fc34
	ibus-anthy-python 1.5.12-6.fc34 -> 1.5.12-4.fc34
	ibus-hangul 1.5.4-5.fc34 -> 1.5.4-4.fc34
	ibus-libpinyin 1.12.0-3.fc34 -> 1.12.0-2.fc34
	libtracker-sparql 3.1.1-2.fc34 -> 3.1.1-1.fc34
	pam 1.5.1-5.fc34 -> 1.5.1-3.fc34
	qt-settings 34.5-1.fc34 -> 34.4-1.fc34
	tracker 3.1.1-2.fc34 -> 3.1.1-1.fc34
Removed:
	xhost-1.0.7-2.fc34.x86_64
	xmodmap-1.0.9-2.fc34.x86_64
	xrdb-1.1.1-2.fc34.x86_64
Added:
	libmcpp-2.7.2-27.fc34.x86_64
	mcpp-2.7.2-27.fc34.x86_64
	xorg-x11-server-utils-7.7-39.fc34.x86_64
```

**Comment by tpopela** [comment] 2021-04-26 11:34
Hi @arteeh ! Can you please try to reproduce it with up to date Fedora Workstation 34 inside a VM (se we can see whether it's a Silverblue specific or not). But looking at the packages I don't think it will be SB specific - Looking at gnome-shell 40.0-3.fc34 -> 40.0-1.fc34 -> I will ask the GNOME Shell devs whether they have some idea. Also do you see something in journal?

**Comment by arteeh** [comment] 2021-04-26 13:00
I booted the latest Workstation 34 Beta iso and was able to reproduce the issue in the 'Try Fedora' section. I didn't do a full install but I assume the problem will be the same there.

Here's what it looks like. I can click around (and e.g. log out), but most things, including icons in the app grid won't show.

![workstation](https://user-images.githubusercontent.com/35239587/116086191-d5170a80-a69f-11eb-8560-06bb0276d002.PNG)

A VM with Arch installed has the same problem, but with slightly different looking symptoms:

![arch](https://user-images.githubusercontent.com/35239587/116085897-92553280-a69f-11eb-9289-46b7c0e6123c.PNG)

I took a quick peek at journalctl but the following line (which shows up several times in a row) is the only thing I could find that might be noteworthy:

`Apr 26 14:44:58 vm kernel: [drm:vmw_msg_ioctl [vmwgfx]] *ERROR* Failed to open channel.`

**Comment by arteeh** [comment] 2021-04-26 13:07
I've found out that switching off 'Enable 3D acceleration' in the VM settings removes the issue.

**Comment by tpopela** [comment] 2021-04-26 14:53
According to one of the GNOME Shell/Mutter developers it looks like a problem in the vmwgfx driver (as the journal entry suggests). Please open a ticket in the [bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?component=kernel&product=Fedora&version=34) and paste it here please.

**Comment by arteeh** [comment] 2021-04-26 19:35
Ticket opened: https://bugzilla.redhat.com/show_bug.cgi?id=1953740

**Comment by tpopela** [comment] 2021-04-27 07:35
Thank you @arteeh ! I'm closing this ticket then.

**Closed by tpopela** 2021-04-27 07:35 UTC
