### ISSUE TITLE
Silverblue 33: rpm is still using Berkeley DB, not sqlite.

### ISSUE THREAD

**Issue by hansborr** [fedora-silverblue/issue-tracker#118] opened 2020-12-19 22:30 UTC
In Fedora 33, rpm moved to the sqlite backend, with Berkeley DB support being removed in F34.
For context/reference, see https://fedoraproject.org/wiki/Changes/Sqlite_Rpmdb and https://bugzilla.redhat.com/show_bug.cgi?id=1836108

Even fresh installs of silverblue 33 end up with the Berkeley DB in use, which triggers warnings when using rpm.

I see that rpm for rpm has a post-transaction scriptlet which touches /var/lib/rpm/.rebuilddb if /var/lib/rpm/Packages exists, which would then trigger rpmdb-rebuild.service to force a rebuild on the next boot.

However, it looks like this never works on my system: the touch file /var/lib/rpm/.rebuilddb file does not exist, so rpmdb-rebuild.service never triggers.

I expect that even if rpmdb-rebuild.service triggered properly, it would still fail since /var/lib/rpm is symlinked to /usr/share/rpm/ which is a read-only filesystem.
Aside from that, the selinux labels on the contents of /usr/share/rpm/ are wrong and restorecon doesn't attempt to fix them. Even if the read-only filesystem weren't a problem, I think selinux errors would prevent rpmdb-rebuild.service from functioning.

The workaround of manually rebuilding the rpmdb to force it to convert to sqlite is not possible on silverblue, due to the usage of the read-only filesystem.

I am not sure what the best solution for this problem is.

**Comment by tpopela** [comment] 2020-12-20 07:47
Duplicate of #95

**Closed** 2020-12-20 07:47 UTC
