### ISSUE TITLE
[RFE] Push silverblue & kinoite images to Fedora registry or quay

### ISSUE THREAD

**Issue by anthr76** [fedora-silverblue/issue-tracker#275] opened 2022-05-11 18:24 UTC
**Is your feature request related to a problem? Please describe.**

A few users and I would like to take advantage of rpm-ostree's newest container derivation features. Without the project publishing containers for Silverblue and Kinoite users must first build the tree from workstation-ostree-config.

**Describe the solution you'd like**

I would like to have whatever desktop ostree variants published to a container registry similar to:

* https://github.com/coreos/fedora-coreos-tracker/issues/1171
* https://quay.io/repository/coreos-assembler/fcos?tab=tags

**Describe alternatives you've considered**

Doing the work myself.

**Additional context**

I'd be happy to help but need some pointers on where to look. I did find [this](https://pagure.io/fedora-kickstarts/tree/main) but not sure that's the right place to be looking...

The container ideally should be pushed when the tree is built (I imagine)

**Comment by cgwalters** [comment] 2022-05-11 18:34
I thinks this overlaps with https://pagure.io/releng/issue/10399 - probably best to ping there.

**Comment by travier** [comment] 2024-01-22 10:44
Going to close this one as a duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/359

**Closed by travier** 2024-01-22 10:44 UTC
Labels: enhancement
