### ISSUE TITLE
rpm-ostree update fails due to:  Sanity-checking final rpmdb

### ISSUE THREAD

**Issue by jasek5** [fedora-silverblue/issue-tracker#130] opened 2021-02-19 08:08 UTC
Hi, I am having problem with updating (at least about 2 weeks).
I cant update/upgrade (`rpm-ostree update` / `rpm-ostree upgrade`) due to 
`error: Sanity-checking final rpmdb: Didn't find package 'SDL2-2.0.14-1.fc33.x86_64' `
I honestly do not know what to do..
Could you please guide me to fix this error ?
If you need any more outputs please just ask and i will provide them to you.

```
rpm-ostree:
 Version: '2021.1'
 Git: 6e7c0b5635f61c88fb8f93c5ec55cc692312cb48
 Features:
  - compose
  - rust
  - fedora-integration
                                               

```

**Comment by tpopela** [comment] 2021-02-19 08:49
Hi @jasek5 ! What's the output of `rpm -qa | grep 'rpm-ostree\|libsolv'`?

**Comment by jasek5** [comment] 2021-02-19 09:57
Hi, thank you for helping me 
Output:
`warning: Found bdb Packages database while attempting sqlite backend: using bdb backend.
rpm-ostree-libs-2021.1-2.fc33.x86_64
gnome-software-rpm-ostree-3.38.0-2.fc33.x86_64
rpm-ostree-2021.1-2.fc33.x86_64
libsolv-0.7.17-1.fc33.x86_64
`

**Comment by tpopela** [comment] 2021-02-19 10:21
Duplicate of #124

**Closed by tpopela** 2021-02-19 10:21 UTC

**Comment by jasek5** [comment] 2021-02-19 10:36
Thank you !
I solved it !
Could you please describe briefly what was wrong or why I have to do that?

**Comment by tpopela** [comment] 2021-02-19 10:38
Everything can be found in the linked issues from there, but this should be the right one:

https://github.com/coreos/rpm-ostree/pull/2490

together with the information mentioned in 

https://bodhi.fedoraproject.org/updates/FEDORA-2021-937b45bf55

**Comment by jasek5** [comment] 2021-02-19 10:38
Thank you very much
