### ISSUE TITLE
[BUG] using lchsh to change the shell brings user back to fedora setup

### ISSUE THREAD

**Issue by axtloss** [fedora-silverblue/issue-tracker#307] opened 2022-07-03 10:37 UTC
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
When using lchsh to change the default shell (in this case to fish), the user gets brought back to the first-boot/fedora setup screen, where they are prompted to create a new user.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. run `sudo lchsh <username>`
2. follow the lchsh instructions and properly change the shell
3. reboot silverblue
4. get brought to the setup screen

**Expected behavior**
The shell should change and the user should be able to log into their user normally, without having to go through the setup again.

**Screenshots**
-

**OS version:**
```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: inactive
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220702.0 (2022-07-02T01:29:19Z)
                BaseCommit: 3afc1bafc3fbada0e16fe7579d4612f732d9f71c3bafe928e49f2699bdd77c65
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
       RemovedBasePackages: firefox 102.0-1.fc36
           LayeredPackages: akmod-nvidia binutils fish kitty langpacks-en libinput-utils wmctrl xorg-x11-drv-nvidia-cuda
             LocalPackages: rpmfusion-free-release-36-1.noarch rpmfusion-nonfree-release-36-1.noarch

AvailableUpdate:
        Version: 36.20220703.0 (2022-07-03T00:41:13Z)
         Commit: 48cc35cbf01e890bbaa1fe0589a8115781d2595b842f2632dc61db27572ef855
   GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           Diff: 9 upgraded
```

**Additional context**
The original user still exists, and once the user goes through the setup and creates a new user they can still log into the old user, the shell is also succesfully changed.

**Comment by travier** [comment] 2022-07-03 13:44
I don't now what's the root cause of this specific bug but in general, my recommendation is to not change the login shell of users in Silverblue. You never know when you will need to reset the overrides and once you do that, you won't be able to login as the shell will not exists anymore.

Instead, you can add something to your bashrc that checks if the shell that you want is installed and then execute it by default.

**Comment by CheariX** [comment] 2022-08-20 12:56
> Instead, you can add something to your bashrc that checks if the shell that you want is installed and then execute it by default.

I added the following to my `.bashrc`:
```sh
if [ -f /usr/bin/fish ]; then
    exec /usr/bin/fish
fi
```
Also it works as long as you are logged in, I could no longer login using GDM after a restart.
So, I cannot recommend this code snippet (maybe there must be some additional checks).

**Comment by travier** [comment] 2022-08-20 14:07
You probably want something like (untested):
```
if [[ $- == *i* ]]  && [[ -f /usr/bin/fish ]]; then
    exec /usr/bin/fish "$@"
fi
```
from https://unix.stackexchange.com/questions/26676/how-to-check-if-a-shell-is-login-interactive-batch

**Comment by david-burkett** [comment] 2022-08-28 23:15
Hello - this actually happened to me as well. Verify that your new shell actually installed properly (try and enter it from the new user). When I had this happen, it was because for whatever reason when I ran `rpm-ostree install zsh` it didn't actually apply it until I did a `grub2-mkconfig` and it wasn't seeing the binary. If you do a:

```
sudo nano /etc/passwd
```
And change the shell back to `/bin/bash` and sign out and on your regular user do a `sudo userdel $NEW_USER_HERE` to get rid of any temp users you may have created from this.

Hope this helps!

**Comment by travier** [comment] 2023-05-15 16:12
From my perspective, this is not an issue in Silverblue. We should deprecate allowing changing the users shell entirely but that's a much larger change. See https://github.com/fedora-silverblue/issue-tracker/issues/307#issuecomment-1173092416 for more details.

Fedora 36 is about to go EOL so I'll close this issue. Please provide updated information if this is still an issue.

**Comment by travier** [comment] 2023-05-15 16:12
We welcome docs PRs to document this issue in the documentation.

**Closed by travier** 2023-05-15 16:12 UTC
Labels: bug, need-info, f36
