### ISSUE TITLE
Installation of Fedora Silverblue 37 is terminated with error

### ISSUE THREAD

**Issue by jirihnidek** [fedora-silverblue/issue-tracker#425] opened 2023-02-28 17:31 UTC
**Describe the bug**
Installation of Fedora Silverblue 37 is terminated with error

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Boot laptop Lenovo Thinkpad P1 (silverblue installation image was on flash disk)
2. Configure Anaconda installer to use brtfs and encrypt disk. (I clicked "Use default partitioning" for partitioning of my disk)
3. Start installation process

**Expected behavior**
OS is installed on the laptop

**Screenshots**
![fedora-silverblue-screenshot](https://user-images.githubusercontent.com/2057012/221930255-346ce5fb-9417-439e-9ec2-cc398671f765.jpeg)

**OS version:**
I used this image for installation: Fedora-Silverblue-ostree-x86_64-37-1.7.iso

**Additional context**
I tried two flash disks with the same results. I don't know if the issue is caused by encryption of disk. I didn't try to install silverblue without encryption of the disk, because I just need it. I was able to install Fedora Workstation 37 on the laptop without any problem.

**Comment by miabbott** [comment] 2023-02-28 19:00
This looks like https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_unable_to_install_fedora_silverblue_on_efi_systems

See also https://bugzilla.redhat.com/show_bug.cgi?id=1575957

**Comment by jirihnidek** [comment] 2023-03-01 10:09
Yeah, I didn't reformat existing EFI partition and installer automatically tried to mount it on /boot/efi

**Comment by travier** [comment] 2023-03-01 14:27
Closing as duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/284

**Closed by travier** 2023-03-01 14:27 UTC
Labels: bug
