### ISSUE TITLE
No wayland session after rebase to Silverblue 39 Beta

### ISSUE THREAD

**Issue by alvaroburns** [fedora-silverblue/issue-tracker#494] opened 2023-09-28 22:38 UTC
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in [Red Hat Bugzilla](https://bugzilla.redhat.com/) (see [How to file a bug](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/)) or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
After I rebased to Silverblue 39 Beta from 38, I have no wayland session. The gear icon shows "GNOME" and "GNOME Classic", but both of them are using X11.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
Rebase from 38 to 39 using the command rpm-ostree rebase fedora:fedora/39/x86_64/silverblue and reboot

**Expected behavior**
Wayland by default and the option to change using the gear icon on the login screen.

**Screenshots**

![Captura de tela de 2023-09-28 19-26-59](https://github.com/fedora-silverblue/issue-tracker/assets/146345495/4132fdca-c8f7-409c-88df-47d56019ab92)
![Captura de tela de 2023-09-28 19-26-32](https://github.com/fedora-silverblue/issue-tracker/assets/146345495/d474290f-6248-4492-949e-c9c9a215cd5b)

**OS version:**
Fedora Silverblue 39.20230928.0

**Additional context**
I don't have a nvidia card or something.

**Comment by realgrm** [comment] 2023-09-29 01:11
Same issue here with the same hardware (Lenovo IdeaPad Flex 5 14IIL05).
Reproduced also with a Fedora Workstation 39 Live CD Session.

**Comment by travier** [comment] 2023-09-29 09:30
Does this also happens if you reset your overrides?

**Comment by alvaroburns** [comment] 2023-09-29 09:51
> Does this also happens if you reset your overrides?

Yes, it does. I tried with and without the overrides.

**Comment by travier** [comment] 2023-09-29 09:54
CC @tpopela

**Comment by alvaroburns** [comment] 2023-09-29 11:12
> > Reproduced also with a Fedora Workstation 39 Live CD Session.
> 
> Then this looks like something not Silverblue specific and should be filed in Bugzilla and submitted as a blocker for the F39 release.

https://bugzilla.redhat.com/show_bug.cgi?id=2241332

**Comment by nielsdg** [comment] 2023-10-02 12:57
FWIW, I can't reproduce on my system (a Thinkpad X1 Carbon Gen 8) after upgrading to Silverblue

**Comment by nielsdg** [comment] 2023-10-03 13:25
So the issue we're actually seeing is https://bugzilla.redhat.com/show_bug.cgi?id=2238711 . I closed the linked BZ as a duplicate of that one

**Comment by fxamacker** [comment] 2024-01-03 05:24
Should this issue be closed?

Latest comment at https://bugzilla.redhat.com/show_bug.cgi?id=2238711 is
> FEDORA-2023-86e10b6cae has been pushed to the Fedora 39 stable repository.
> If problem still persists, please make note of it in this bug report.

**Comment by travier** [comment] 2024-01-03 13:42
Yes, thanks!

**Closed by travier** 2024-01-03 13:42 UTC
Labels: bug, upstream, f39
