### ISSUE TITLE
Boot fails with "vmlinuz has invalid signature" or "bad shim signature, you need to load the kernel first"

### ISSUE THREAD

**Issue by Mershl** [fedora-silverblue/issue-tracker#543] opened 2024-03-28 20:10 UTC
# Current workaround

**See https://github.com/fedora-silverblue/issue-tracker/issues/543#issuecomment-2048350047**

---

# Original issue text

**Describe the bug**
Trying to rebase an existing SB39 to SB40 fails to boot showing `vmlinuz-6.8.1-300.fc40.x86.x64 has invalid signature. you need to load the kernel first` on an Thinkpad T495. I was not able to reproduce the issue on my desktop systems.

coming from deployment:
```
fedora:fedora/39/x86_64/silverblue
                  Version: 39.20240328.0 (2024-03-28T00:39:32Z)
               BaseCommit: a1ac8885d05ca13728d92c2bcf1ded67a7ddb409d657e446a808397366a463b1
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
```

going for:
```
fedora:fedora/40/x86_64/silverblue
                  Version: 40.20240328.n.0 (2024-03-28T08:09:28Z)
               BaseCommit: f726d0be3361a42a8ac175b08851de67a2d97c9c01ee130a3abcd32720120f9c
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
```

**What I've tried so far**
- cleanup + `rpm-ostree initramfs --enable` + rebase
- `cleanup -r` (removing all other deployments) + rebase
- rebase to `fedora:fedora/40/x86_64/testing/silverblue` instead, same error except error message points to vmlinuz-6.8.2

**To Reproduce**
1. `rpm-ostree rebase fedora:fedora/40/x86_64/silverblue`
2. `systemctl reboot`

**Comment by travier** [comment] 2024-03-29 10:45
I've hit the same issue and I've disabled Secure Boot for now.

It's likely due to the bootloader being too old. bootupd should land in the image after the release and will then let people update their bootloader.

Or maybe we should include bootupd in Fedora 39 now so that people can update their bootloader before upgrading to Fedora 40.

**Comment by Mershl** [comment] 2024-04-07 11:13
Oh Oh.

SB39 just updated to kernel 6.8.4 showing the very same issue.

```
  kernel 6.7.11-200.fc39.x86_64 -> 6.8.4-200.fc39.x86_64
```

breaks boot, showing

```
vmlinuz-6.8.4-200.fc39.x86_64 has invalide signature.
you need to load the kernel first.
```

(Thinkpad T495)

**Comment by travier** [comment] 2024-04-08 15:41
Pinging Universal Blue folks as it's likely going to impact them soon: @castrojo @noelmiller @EyeCantCU @KyleGospo

**Comment by travier** [comment] 2024-04-09 16:38
Unfortunately, now that the kernel has landed in an update, we can not add bootupd to a future F39 build as you won't be able to boot it to get the fix.

Overlaying bootupd via `rpm-ostree install` is not enough as it needs to run a command during the commit build process.

So we have https://github.com/coreos/bootupd/issues/635 as an option (that I have not tested yet) to create container images with bootupd based on an older commit with the previous kernel.

Or we document how to manually fix this until bootupd finally lands in Atomic Desktops. Unfortunately it will not fully be in Fedora 40 by default yet. See: https://gitlab.com/fedora/ostree/sig/-/issues/1

**Comment by hferreiro** [comment] 2024-04-09 19:50
Can't the update to the kernel package be reverted in the same commit that bootupd is added?

**Comment by travier** [comment] 2024-04-09 19:54
No unfortunately, for Fedora Atomic Desktops, we always take the latest RPMs from the repos.

**Comment by jorgeml** [comment] 2024-04-10 15:59
@travier I'm watching this one with interest as my Silverblue image is now one week old. If I understand it correctly, the only solution at the moment is to disable Secure Boot? And not even upgrading to Fedora 40 will solve it in the near future?

**Comment by travier** [comment] 2024-04-10 18:31
The workaround for this issue is going to be commands that do what bootupd does but manually unfortunately.

This is mostly doing a copy from `/usr/lib/ostree-boot` to `/boot/efi` on EFI systems, and a `/usr/sbin/grub2-install` call on BIOS ones, with the correct arguments.

I have not tested any of this so I'm not providing ready made commands and everything is at your own risk. Help with testing in VMs or on real hardware is welcomed.

I recommend disabling Secure Boot in the meantime until this is fixed.

**Comment by travier** [comment] 2024-04-10 20:06
**Warning: Do at your own risk, only lightly tested**

Here is the set of commands I've just used to update my (x86_64) EFI booted system successfully:

```
# Enter a root shell on the host (i.e. not in a toolbox)
$ sudo -i

# Make a backup of the content of the EFI partition
$ cd /boot/efi/EFI/
$ cp -a BOOT BOOT.bkp
$ cp -a fedora/ fedora.bkp

# Copy updated bootloader versions
$ cp /usr/lib/ostree-boot/efi/EFI/BOOT/{BOOTX64.EFI,fbx64.efi} /boot/efi/EFI/BOOT/
$ cp /usr/lib/ostree-boot/efi/EFI/fedora/{BOOTX64.CSV,grubx64.efi,mmx64.efi,shim.efi,shimx64.efi} /boot/efi/EFI/fedora/
$ cp /usr/lib/ostree-boot/efi/EFI/fedora/shimx64.efi /boot/efi/EFI/fedora/shimx64-fedora.efi

# Sync changes to the disk
$ sync

# Reboot
```

**Comment by jorgeml** [comment] 2024-04-10 20:23
Thanks @travier ! Just did this on my machine and it worked. I was also able to reenable Secure Boot. As a positive side effect, it also looks like the UEFI dbx update was applied. That had been blocked for a while.

**Comment by cgwalters** [comment] 2024-04-11 13:14
OK sorry yes, this is an embarrassing problem.

@travier and I had a chat, a few things here:

- We can safely add bootupd to f39
- I think we can also document a flow of `rpm-ostree upgrade` but *without* restarting, then
- Run bootupd from the new root

Alternatively, we can document how to run bootupd from a privileged container.  (In fact, running it from the existing `quay.io/fedora/fedora-coreos:stable` container for example.  One minor stumbling block here is that bootupd wants to act in a client/server model with systemd, but I think we can change it to not do that)

Longer term yes, the technical debt here is high and makes https://github.com/coreos/bootupd/issues/454 important to do and just turn on automatic updates, or at least automatic updates when they're needed.

**Comment by Mershl** [comment] 2024-04-11 18:56
> Copy updated bootloader versions
> $ cp /usr/lib/ostree-boot/efi/EFI/BOOT/{BOOTIA32.EFI,BOOTX64.EFI,fbia32.efi,fbx64.efi} /boot/efi/EFI/BOOT/
> $ cp /usr/lib/ostree-boot/efi/EFI/fedora/{BOOTIA32.CSV,BOOTX64.CSV,grubia32.efi,grubx64.efi,mmia32.efi,mmx64.efi,shim.efi,shimia32.efi,shimx64.efi} /boot/efi/EFI/fedora/
> 
> Only needed if it exists already on your system
> $ cp /usr/lib/ostree-boot/efi/EFI/fedora/shimx64.efi /boot/efi/EFI/fedora/shimx64-fedora.efi

@travier I've noticed that the affected Thinkpad T495 was missing `boot/efi/EFI/BOOT` completely. I skipped the line in your test steps and it worked out perfectly. SecureBoot reenabled, no regressions found so far.

Looking into other systems I see the mentioned `boot/efi/EFI/BOOT`. Does someone know the difference, does it depend on the birth date of the Fedora/Silverblue installation?

**Comment by A6GibKm** [comment] 2024-04-13 17:39
> **Warning: Do at your own risk, only lightly tested**
> 
> Here is the set of commands I've just used to update my (x86_64) EFI booted system successfully:
> 
> ```
> # Enter a root shell on the host (i.e. not in a toolbox)
> $ sudo -i
> 
> # Make a backup of the content of the EFI partition
> $ cd /boot/efi/
> $ cp -a EFI EFI.bkp
> 
> # Copy updated bootloader versions
> $ cp /usr/lib/ostree-boot/efi/EFI/BOOT/{BOOTIA32.EFI,BOOTX64.EFI,fbia32.efi,fbx64.efi} /boot/efi/EFI/BOOT/
> $ cp /usr/lib/ostree-boot/efi/EFI/fedora/{BOOTIA32.CSV,BOOTX64.CSV,grubia32.efi,grubx64.efi,mmia32.efi,mmx64.efi,shim.efi,shimia32.efi,shimx64.efi} /boot/efi/EFI/fedora/
> 
> # Only needed if it exists already on your system
> $ cp /usr/lib/ostree-boot/efi/EFI/fedora/shimx64.efi /boot/efi/EFI/fedora/shimx64-fedora.efi
> 
> # Sync changes to the disk
> $ sync
> 
> # Reboot
> ```
> 
> Once reboot is successful, you can remove the backup copies:
> 
> ```
> # Enter a root shell on the host (i.e. not in a toolbox)
> $ sudo -i
> 
> # Make a backup of the content of the EFI partition
> $ cd /boot/efi/
> $ rm -ri ./EFI.bkp
> 
> # Sync changes to the disk
> $ sync
> ```
> 
> Edit: Updated to add 32bits EFI binaries as well.

I tested these steeps on my workstation and my Thinkpad T480. I managed to get secure boot on both devices.

On the desktop I had to use fwupdmgr to update the UEFI dbx.

**Comment by rugk** [comment] 2024-04-25 09:50
[Has the same issue reported here](https://discussion.fedoraproject.org/t/boot-issue-grub-in-fedora-silverblue-after-upgrading-latest-known-working-39-20240325-0-error-ostree-vmlinuz-has-invalid-signature-kernel-6-8-6-200-fc39/113484) ([also includes a kernel bug report](https://bugzilla.redhat.com/show_bug.cgi?id=2276099) though I am unsure how helpful that is), so, but this question AFAIK remains unanswered:

> And not even upgrading to Fedora 40 will solve it in the near future?

So does updating fix it? I mean I can boot into an old working Fedora 39 version.
If I upgrade from there to Fedora 40, does that work?

Alternatively, if I need to disable Secure Boot temporarily, can I just do so – upgrade to Fedora 40 and boot successfully, afterwards?

Also, would this possibly be a candidate for [a common issue](https://discussion.fedoraproject.org/tags/c/ask/common-issues/82/none/f40) if it prevents upgrading to Fedora 40?

**Comment by travier** [comment] 2024-04-25 11:44
It's a good idea to make it a common issue.

It's basically impossible to fix automatically right now for F39 users updating as the new kernel already landed in Fedora 39.

We'll try to get bootupd support to a sufficiently good shape to have a small set of commands to enter manually but in the meantime, the commands in https://github.com/fedora-silverblue/issue-tracker/issues/543#issuecomment-2048350047 are the best that we have.

**Comment by rugk** [comment] 2024-04-25 15:00
Okay then, I have created a draft for this here:
https://discussion.fedoraproject.org/t/booting-fails-with-vmlinuz-has-invalid-signature/114354

Unfortunately I miss the technical details etc. to properly document it. So feel free to edit it please.

**Comment by rugk** [comment] 2024-04-29 22:16
FYI I can confirm the workaround posted worked:
```
# tree EFI
EFI
├── BOOT
│   ├── BOOTIA32.EFI
│   ├── BOOTX64.EFI
│   ├── fbia32.efi
│   └── fbx64.efi
└── fedora
    ├── BOOTIA32.CSV
    ├── BOOTX64.CSV
    ├── fonts
    ├── grub.cfg
    ├── grub.cfg.old
    ├── grubenv
    ├── grubenvLa7zjw
    ├── grubia32.efi
    ├── grubx64.efi
    ├── mmia32.efi
    ├── mmx64.efi
    ├── shim.efi
    ├── shimia32.efi
    ├── shimx64.efi
    └── shimx64-fedora.efi

4 directories, 18 files
# tree EFI.bkp/
EFI.bkp/
├── BOOT
│   ├── BOOTX64.EFI
│   └── fbx64.efi
└── fedora
    ├── BOOTX64.CSV
    ├── fonts
    ├── grub.cfg
    ├── grub.cfg.old
    ├── grubenv
    ├── grubenvLa7zjw
    ├── grubx64.efi
    ├── mmx64.efi
    ├── shim.efi
    ├── shimx64.efi
    └── shimx64-fedora.efi

```

**Comment by fbruetting** [comment] 2024-05-02 12:28
> **Warning: Do at your own risk, only lightly tested**
> 
> Here is the set of commands I've just used to update my (x86_64) EFI booted system successfully:
> 
> ```
> # Enter a root shell on the host (i.e. not in a toolbox)
> $ sudo -i
> 
> # Make a backup of the content of the EFI partition
> $ cd /boot/efi/
> $ cp -a EFI EFI.bkp
> 
> # Copy updated bootloader versions
> $ cp /usr/lib/ostree-boot/efi/EFI/BOOT/{BOOTIA32.EFI,BOOTX64.EFI,fbia32.efi,fbx64.efi} /boot/efi/EFI/BOOT/
> $ cp /usr/lib/ostree-boot/efi/EFI/fedora/{BOOTIA32.CSV,BOOTX64.CSV,grubia32.efi,grubx64.efi,mmia32.efi,mmx64.efi,shim.efi,shimia32.efi,shimx64.efi} /boot/efi/EFI/fedora/
> 
> # Only needed if it exists already on your system
> $ cp /usr/lib/ostree-boot/efi/EFI/fedora/shimx64.efi /boot/efi/EFI/fedora/shimx64-fedora.efi
> 
> # Sync changes to the disk
> $ sync
> 
> # Reboot
> ```
> 
> Once reboot is successful, you can remove the backup copies:
> 
> ```
> # Enter a root shell on the host (i.e. not in a toolbox)
> $ sudo -i
> 
> # Make a backup of the content of the EFI partition
> $ cd /boot/efi/
> $ rm -ri ./EFI.bkp
> 
> # Sync changes to the disk
> $ sync
> ```
> 
> Edit: Updated to add 32bits EFI binaries as well.

Thereafter, I get the following:

After `rpm-ostree update`:
```terminal-session
…
…
Writing OSTree commit... done
Staging deployment... done
error: Staging deployment: Cleaning deployments: Removing ostree/deploy/fedora/deploy/3fd29d12b510aabcc32bd5ab5a6262b4d1a4da43efc7a70788c11837f1afa140.0: unlinkat(classic-topbar-network-cellular-acquiring.svg): Das Dateisystem ist nur lesbar (engl.: „File system is read-only“)
```

At second try:
```terminal-session
❯ LANG=en_US.utf8; rpm-ostree update
error: Remounting /sysroot read-write: Das Argument ist ungültig (engl.: „Argument not valid“)
```

**Comment by rugk** [comment] 2024-05-02 13:56
@fbruetting seems like a different issue, OSTree updates should not have anything to do with the bootloader update. Maybe ask at the Fedora discussions forum for help?

**Comment by mcejp** [comment] 2024-05-10 23:27
FWIW, I have ran into this error on Fedora _Workstation_ 39. The root cause was that in my /etc/fstab, the `/boot/efi` entry was commented out (for many years, apparently). The package manager thought it was updating the EFI binaries, but instead they were going into a subdirectory of /boot.

**Comment by maksimsamt** [comment] 2024-06-17 09:48
My story.
Upgrade was successful from f39 => f40 (ostree).
It worked without problems for a while.
Today applied upgrade kernel from 6.8.11 to 6.9.4.
After reboot got this error:
```log
error: ../../grub-core/kern/efi/sb.c:182:bad shim signature
error: .././grub-core/loader/i1386/efi/linux.c:258:you need to load the kernel first
```
Secure boot enabled.
Workaround https://github.com/fedora-silverblue/issue-tracker/issues/543#issuecomment-2048350047 works and now secure boot works with updated kernel 6.9.4

**Comment by RobotRoss** [comment] 2024-06-17 14:47
> **Warning: Do at your own risk, only lightly tested**
> 
> Here is the set of commands I've just used to update my (x86_64) EFI booted system successfully:
> 
> ```
> # Enter a root shell on the host (i.e. not in a toolbox)
> $ sudo -i
> 
> # Make a backup of the content of the EFI partition
> $ cd /boot/efi/
> $ cp -a EFI EFI.bkp
> 
> # Copy updated bootloader versions
> $ cp /usr/lib/ostree-boot/efi/EFI/BOOT/{BOOTIA32.EFI,BOOTX64.EFI,fbia32.efi,fbx64.efi} /boot/efi/EFI/BOOT/
> $ cp /usr/lib/ostree-boot/efi/EFI/fedora/{BOOTIA32.CSV,BOOTX64.CSV,grubia32.efi,grubx64.efi,mmia32.efi,mmx64.efi,shim.efi,shimia32.efi,shimx64.efi} /boot/efi/EFI/fedora/
> 
> # Only needed if it exists already on your system
> $ cp /usr/lib/ostree-boot/efi/EFI/fedora/shimx64.efi /boot/efi/EFI/fedora/shimx64-fedora.efi
> 
> # Sync changes to the disk
> $ sync
> 
> # Reboot
> ```
> 
> Once reboot is successful, you can remove the backup copies:
> 
> ```
> # Enter a root shell on the host (i.e. not in a toolbox)
> $ sudo -i
> 
> # Make a backup of the content of the EFI partition
> $ cd /boot/efi/
> $ rm -ri ./EFI.bkp
> 
> # Sync changes to the disk
> $ sync
> ```
> 
> Edit: Updated to add 32bits EFI binaries as well.

Just encountered this on an existing F40 install, following the steps to manually upgrade shimx64.efi worked.

**Comment by JAORMX** [comment] 2024-06-18 04:58
Just stumbled upon this on `Fedora Linux 40.20240617.0 (Silverblue)`

**Comment by awarda-rh** [comment] 2024-06-18 06:38
Thanks, this also fixed the issue with me. 

For context, see:
https://bugzilla.redhat.com/show_bug.cgi?id=2150982
https://bugzilla.redhat.com/show_bug.cgi?id=2150982

**Comment by benkei-kuruma** [comment] 2024-06-18 17:25
Same issue here with my five automatically updating Silverblue 40 machines. @travier 's workaround fixed it, didn't have to disable secure boot. Thank you!

For what it's worth, this is actually the first time in ~2.5 years using Silverblue exclusively that I haven't been able to boot into my OS.

**Comment by TXort** [comment] 2024-06-18 23:25
Same issue, broke on both laptop and PC.

The script mentioned above worked. Thanks!

@benkei-kuruma 
Interesting, I have been using Silverblue for a few months now and after this I am thinking to go back to Workstation since it never failed me.

**Comment by benkei-kuruma** [comment] 2024-06-19 01:25
> Same issue, broke on both laptop and PC.
> 
> The script mentioned above worked. Thanks!
> 
> @benkei-kuruma Interesting, I have been using Silverblue for a few months now and after this I am thinking to go back to Workstation since it never failed me.

I hear you. 

Honestly, this isn't a showstopper for me by any means.  It sounds like they've already identified the boot updater issue as "severe" and are working hard to fix it. I was more giving them a compliment that an "experimental" OS like Silverblue has otherwise been so reliable for me. These devs are awesome.

To gush a bit, I absolutely adore Silverblue, it's hands down the best OS I've ever used. After years upon years of distrohopping, this is the longest I've been on one distro exclusively, to the point where I don't even read about Linux much anymore these days. To me, so many distros are basically the same thing in different wrapping paper, while Silverblue feels totally fresh and revolutionary. I love it. 🙂

**Comment by aidzmtsk** [comment] 2024-06-19 07:28
Seems like this issue has finally caught up to me with the update to Linux Kernel 6.9.4.
Thanks to the ability to rollback, I was able to boot into my system. While the fact that I couldn't boot at all initially was a major showstopper, the ability to rollback saved the day :+1: 
Since I see a bright future for Atomic Desktops, I'm still going to stick with it (after all, I was half-expecting this issue to appear sooner or later). Hopefully, as a not-so-technical user, the workaround works.

**Comment by boydkelly** [comment] 2024-06-21 08:19
Updated this am to 40.20240621 and issue still persists.

**Comment by awarda-rh** [comment] 2024-06-21 10:45
I don't expect this to be resolved with any 40.2024* update.
Use the workaround from [here](https://discussion.fedoraproject.org/t/after-a-system-update-bad-shim-signature-silverblue-f40/120347/2) to manually update the bootloader files.

**Comment by boydkelly** [comment] 2024-06-21 15:00
> I don't expect this to be resolved with any 40.2024* update. Use the workaround from [here](https://github.com/fedora-silverblue/issue-tracker/issues/543#issuecomment-2048350047) to manually update the bootloader files.

Really?   an issue that causes an unbootable (albeit you can roll back) system?

**Comment by travier** [comment] 2024-06-21 15:20
It's "impossible" to fix via an update.

**Comment by aidzmtsk** [comment] 2024-06-21 15:20
> > I don't expect this to be resolved with any 40.2024* update. Use the workaround from [here](https://github.com/fedora-silverblue/issue-tracker/issues/543#issuecomment-2048350047) to manually update the bootloader files.
> 
> Really?   an update that causes an unbootable (albeit you can roll back) system?  I kinda thought that would be the utmost high priority?

The long term solution is [bootupd](https://github.com/coreos/bootupd) but it is not ready yet to be used in the Atomic Desktops. It would've been included in F40 but it was deferred because unfortunately iirc travier was swamped with work at that time.

**Comment by bnordgren** [comment] 2024-06-21 15:25
Workaround above fixed my issue this morning. Going from 39.20240602.0 to 39.20240621.0.

**Comment by Laserology** [comment] 2024-06-21 18:16
Workaround also fixed my issue.

**Comment by travier** [comment] 2024-06-28 15:43
For folks interested in helping us with this issue, I've written a draft for an article to be published on the Fedora Magazine: https://fedoramagazine.org/?p=40664&preview=1&_ppp=2f0e5b87ab

It includes a "simpler" workaround that would benefit from a little bit more testing. I have also not yet looked at the history to find which versions where impacted first so if folks can find that it would be helpful.

Thanks!

**Comment by TimonLukas** [comment] 2024-06-28 21:15
@travier Just tried it (updating from Kinoite 40.20240617.0 to 40.20240628.0), everything worked as expected! Thank you!

**Comment by miabbott** [comment] 2024-06-30 18:13
> It includes a "simpler" workaround that would benefit from a little bit more testing. I have also not yet looked at the history to find which versions where impacted first so if folks can find that it would be helpful.

I did some testing this weekend using a VM and the problem seems to be introduced with the 6.9 kernel in Fedora. I found this affects both Fedora Silverblue 39 (`kernel- 6.9.4-100.fc39`) and Fedora Sliverblue 40 (`kernel-6.9.4-200.fc40`).

The problematic kernel is introduced in the following versions:

- 39.20240617.0 (`2f87250a645076edab387fff73334d123297d22b6a8a47a5e08f2128d83426a5`)
- 40.20240617.0 (`c7bdc9ecab9df0609da0e04b685ca7608174e6cb81d49e1cf4b70b798557018e`)

The preview link to the Fed Mag post has expired, but I used the workaround information in this issue successfully.

**Comment by travier** [comment] 2024-07-01 11:35
Thanks @miabbott !

**Comment by travier** [comment] 2024-07-01 14:05
Update preview: https://fedoramagazine.org/?p=40664&preview=1&_ppp=8e94781824

**Comment by miabbott** [comment] 2024-07-01 17:49
@travier if you want to update the article with IoT information, it looks like the `fedora/stable/x86_64/iot` ref received the affected kernel as part of 40.20240617.0 (62c8ff246886838c8b5df7ca5ff060fccee8705fa7114f3ec47dad0103ac3ba9)

**Comment by miabbott** [comment] 2024-07-02 12:18
@travier See https://discussion.fedoraproject.org/t/update-originated-bad-shim-error/124397

Should we include instructions about bringing Kinoite/Silverlbue 39 up-to-date before performing the workaround?

**Comment by travier** [comment] 2024-07-02 12:28
Ah, that's a good point, we indeed need that :/

**Comment by travier** [comment] 2024-07-02 12:29
Hum, but why did this not happen when I tested on F39? I'll test again.

**Comment by juhp** [comment] 2024-07-03 05:29
Do you want to update the preview link?  (maybe it is only valid until updated or times out?)

**Comment by travier** [comment] 2024-07-03 18:31
Updated again: https://fedoramagazine.org/?p=40664&preview=1&_ppp=71b3c6065a

**Comment by miabbott** [comment] 2024-07-03 19:00
Updates looks good! Thank you for working on this @travier!

**Comment by richiedaze** [comment] 2024-07-04 15:11
Ran into this issue trying to upgrade my old laptop on silverblue 39. Read and followed the above preview article, and now I am on 40. Ty

**Comment by kronenpj** [comment] 2024-07-13 14:58
I’m unable to upgrade to the latest working version mentioned in the article. From a fresh Silverblue 39 installation, updated to 39.20240610.0:

```
root@fedora:~# rpm-ostree deploy 39.20240616.0 
Resolving version '39.20240616.0'
1 metadata, 0 content objects fetched; 592 B transferred in 2 seconds; 0 bytes content written
error: Version 39.20240616.0 not found in fedora:fedora/40/x86_64/silverblue
```

Is there another working version we should be using to test this solution?
Also, is there a way to find a list of all the {release}.{date}.x versions available?

**Comment by travier** [comment] 2024-07-15 11:19
Please don't post the same things in multiple places without linking to it. I've answered inhttps://discussion.fedoraproject.org/t/talk-boot-fails-with-bad-shim-signature-in-atomic-desktops-and-iot/125412/6.

**Comment by jboero** [comment] 2024-08-14 10:53
I've had this problem for a few kernels since 6.9+ and it seems to me Fedora is still offering the old shim-x64 package with the old Fedora secure boot CA. I'm NOT using Silverblue/atomic so the workaround does not seem applicable.

I see the claim this CA signature is considered old and deprecated, but I see no other update in F40 or rawhide packaging. Thoughts? I'd rather not shut off secureboot.

https://discussion.fedoraproject.org/t/after-a-system-update-bad-shim-signature-silverblue-f40/120347/15

```
~> sudo mokutil --list-enrolled
7e68651d52 Fedora Secure Boot CA
~> sudo dnf info shim-x64
Last metadata expiration check: 0:32:23 ago on Wed 14 Aug 2024 11:18:55 AM BST.
Installed Packages
Name         : shim-x64
Version      : 15.8
Release      : 3
Architecture : x86_64
Size         : 3.6 M
Source       : shim-15.8-3.src.rpm
Repository   : @System
From repo    : fedora
Summary      : First-stage UEFI bootloader
URL          : https://github.com/rhboot/shim/
License      : BSD-3-Clause
Description  : Initial UEFI bootloader that handles chaining to a trusted full
             : bootloader under secure boot environments. This package contains the
             : version signed by the UEFI signing service.
```

**Comment by westurner** [comment] 2024-08-14 14:55
Is there a script to detect that a kernel image has the old (or wrong)
signing keys, that can present a message to the user indicating that they
need to enroll a SecureBoot new key of that's what it is?

**Comment by jboero** [comment] 2024-08-14 16:57
> Strangely this is only the case on one of my environments, and the others show the current valid CA. Reinstalling the shim package does nothing. Bizarre.

Aha I found my problem - duplicate vfat ID from a backup copy of the device was present, so the shim was being installed on the wrong one.

**Comment by travier** [comment] 2024-10-30 16:40
We've landed bootupd in Fedora 41 that should finally prevent those issues in the future.

**Closed by travier** 2024-10-30 16:40 UTC
Labels: bug, f39, f40
